import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import BlueprintDoctypesDocTypes_properties from "./BlueprintDoctypesDocTypes_properties";

/**
 * Overrides of ResourceBundle "BlueprintDoctypesDocTypes_properties" for locale "de".
 * @see BlueprintDoctypesDocTypes_properties
 */
ResourceBundleUtil.override(BlueprintDoctypesDocTypes_properties, {
  CMAbstractCode_displayName: "Code",
  CMAbstractCode_description: "Basistyp für Code-Objekte",
  CMAbstractCode_code_displayName: "Code",
  CMAbstractCode_code_description: "Code-Daten",
  CMAbstractCode_code_emptyText: "Geben Sie hier Code-Daten ein.",
  CMAbstractCode_dataUrl_displayName: "Daten-URL",
  CMAbstractCode_dataUrl_description: "URL der Datenquelle",
  CMAbstractCode_dataUrl_emptyText: "Geben Sie hier die URL der Datenquelle ein.",
  CMAbstractCode_description_displayName: "Beschreibung",
  CMAbstractCode_description_description: "Beschreibung",
  CMAbstractCode_description_emptyText: "Geben Sie hier die Beschreibung ein.",
  CMAbstractCode_ieExpression_displayName: "IE include Ausdruck",
  CMAbstractCode_ieExpression_description: "Internet Explorer-spezifischer Include Ausdruck, z. B. \"if lte IE 7\"",
  CMAbstractCode_ieExpression_emptyText: "",
  CMAbstractCode_ieRevealed_displayName: "",
  CMAbstractCode_ieRevealed_description: "",
  CMAbstractCode_include_displayName: "Benötigter Code",
  CMAbstractCode_include_description: "Benötigter Code, der zusätzlich geladen werden soll",
  CMJavaScript_displayName: "JavaScript",
  CMJavaScript_description: "JavaScript-Code",
  CMJavaScript_inHead_displayName: "Im HTML Head einbinden",
  CMJavaScript_inHead_description: "Diese Einstellung bewirkt die Einbindung im HTML Head.",
  CMJavaScript_code_displayName: "JavaScript-Daten",
  CMJavaScript_code_description: "JavaScript-Daten",
  CMJavaScript_include_displayName: "Benötigte JavaScript-Objekte",
  CMJavaScript_include_description: "Benötigte JavaScript-Objekte",
  CMAction_displayName: "Aktion",
  CMAction_description: "Ein Inhalt, welcher eine Aktion repräsentiert",
  CMAction_id_displayName: "ID",
  CMAction_id_emptyText: "Geben Sie hier die ID ein.",
  CMAction_type_displayName: "Typ",
  CMAction_type_emptyText: "Geben Sie hier den Aktionstyp ein.",
  CMArticle_displayName: "Artikel",
  CMArticle_description: "Artikel",
  CMArticle_title_displayName: "Artikel-Titel",
  CMArticle_title_description: "Titel des Artikels",
  CMArticle_title_emptyText: "Geben Sie hier den Artikeltitel ein.",
  CMArticle_detailText_displayName: "Artikel-Text",
  CMArticle_detailText_description: "Text des Artikels",
  CMArticle_detailText_emptyText: "Geben Sie hier den Text des Artikels ein.",
  CMAudio_displayName: "Audio",
  CMAudio_description: "Objekt mit Audio-Inhalten",
  CMAudio_dataUrl_displayName: "Daten-URL (optional)",
  CMAudio_dataUrl_description: "URL für das Audio-Objekt",
  CMAudio_dataUrl_emptyText: "Geben Sie hier die URL für das Audio-Objekt ein.",
  CMChannel_displayName: "Seite",
  CMChannel_description: "Seite",
  CMChannel_footer_displayName: "Fußzeile",
  CMChannel_footer_description: "Fußzeilen-Objekte",
  CMChannel_footer_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  CMChannel_header_displayName: "Kopfzeile",
  CMChannel_header_description: "Kopfzeilen-Objekte",
  CMChannel_header_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  CMChannel_picture_displayName: "Bild der Seite",
  CMChannel_picture_description: "Bild der Seite",
  CMChannel_title_displayName: "Seitentitel",
  CMChannel_title_description: "Titel der Seite",
  CMChannel_title_emptyText: "Geben Sie hier den Seitentitel ein.",
  CMChannel_placement_displayName: "Bereiche",
  CMChannel_placement_placements_2_layout_displayName: "Layout",
  CMCollection_displayName: "Sammlung",
  CMCollection_description: "Sammlung von Inhalten",
  CMCollection_items_displayName: "Objekte",
  CMCollection_items_description: "Objekte in dieser Sammlung",
  CMCollection_title_displayName: "Sammlungstitel",
  CMCollection_title_description: "Titel der Sammlung",
  CMCollection_title_emptyText: "Geben Sie hier den Sammlungstitel ein.",
  CMContext_displayName: "Navigationskontext",
  CMContext_description: "Navigationskontext",
  CMCSS_displayName: "CSS",
  CMCSS_description: "CSS (Cascading Style Sheets)",
  CMCSS_code_displayName: "CSS-Daten",
  CMCSS_code_description: "CSS-Daten",
  CMCSS_ieRevealed_displayName: "CSS ist sichtbar für Internet Explorer",
  CMCSS_ieRevealed_description: "CSS ist sichtbar für Internet Explorer.",
  CMCSS_media_displayName: "CSS Media Attribut",
  CMCSS_media_description: "Optionales CSS Media-Attribut, z. B. screen",
  CMCSS_include_displayName: "Benötigtes CSS",
  CMCSS_include_description: "Weitere CSS-Objekte, die benötigt werden. z. B. framework",
  Dictionary_displayName: "Dictionary",
  Dictionary_description: "Dictionary",
  CMDownload_displayName: "Download",
  CMDownload_description: "Allgemeiner Download",
  CMDownload_data_displayName: "Binärdaten",
  CMDownload_data_description: "Binärdaten",
  CMDownload_filename_displayName: "Dateiname",
  CMDownload_filename_description: "Der Name der hochgeladenen Datei",
  CMDownload_filename_emptyText: "",
  CMDownload_title_displayName: "Download-Titel",
  CMDownload_title_description: "Titel des Downloads",
  CMDownload_title_emptyText: "Geben Sie hier den Download-Titel ein.",
  CMDynamicList_displayName: "Dynamische Liste",
  CMDynamicList_description: "Liste mit dynamisch berechneten Inhalten",
  CMDynamicList_maxLength_displayName: "Anzahl Einträge",
  CMDynamicList_maxLength_description: "Maximale Anzahl von Inhalten in der Liste",
  CMDynamicList_maxLength_emptyText: "Geben Sie hier die maximale Anzahl von Inhalten in der Liste ein.",
  CMExternalLink_displayName: "Externer Link",
  CMExternalLink_description: "Externer Link",
  CMExternalLink_url_displayName: "URL",
  CMExternalLink_url_description: "URL für den externen Link",
  CMExternalLink_url_emptyText: "Geben Sie hier die URL für den externen Link ein.",
  CMExternalLink_openInNewTab_displayName: "In neuem Tab/Fenster öffnen",
  CMExternalLink_openInNewTab_description: "Abhängig von der Browser-Einstellung wird der externe Link in einem neuem Tab oder Fenster geöffnet.",
  CMFolderProperties_displayName: "Ordnereigenschaften",
  CMFolderProperties_description: "Ordnereigenschaften",
  CMFolderProperties_contexts_displayName: "Kontexte",
  CMFolderProperties_contexts_description: "Kontexte",
  CMFolderProperties_contexts_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  CMGallery_displayName: "Galerie",
  CMGallery_description: "Galerie",
  CMGallery_items_displayName: "Galeriebilder",
  CMGallery_items_description: "Inhalte in dieser Galerie",
  CMGallery_items_emptyText: "Ziehen Sie Bilder aus der Bibliothek hierher.",
  CMGallery_title_displayName: "Galerie-Titel",
  CMGallery_title_description: "Titel der Galerie",
  CMGallery_title_emptyText: "Geben Sie hier den Galerietitel ein.",
  CMGallery_detailText_displayName: "Galerie-Text",
  CMSpinner_displayName: "360°-Ansicht",
  CMSpinner_description: "360°-Ansicht",
  CMSpinner_sequence_displayName: "Bildfolge",
  CMSpinner_sequence_description: "Bildfolge dieser 360°-Ansicht",
  CMSpinner_sequence_emptyText: "Ziehen Sie Bilder aus der Bibliothek hierher.",
  CMSpinner_title_displayName: "Titel",
  CMSpinner_title_description: "Titel der 360°-Ansicht",
  CMSpinner_title_emptyText: "Geben Sie hier den 360°-Ansichtstitel ein.",
  CMSpinner_detailText_displayName: "Beschriftung",
  CMSpinner_detailText_description: "Beschriftung der 360°-Ansicht",
  CMSpinner_detailText_emptyText: "Geben Sie hier die Beschriftung ein.",
  CMHasContexts_displayName: "Inhalt mit Navigationskontext",
  CMHasContexts_description: "Ein Inhalt, welcher einen oder mehrere Navigationskontexte hat",
  CMHasContexts_contexts_displayName: "Navigationskontexte",
  CMHasContexts_contexts_description: "Navigationskontexte, in denen dieses Objekt verfügbar ist.",
  CMHasContexts_contexts_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  CMHTML_displayName: "HTML-Fragment",
  CMHTML_description: "Statisches HTML-Fragment zum Einbinden von beliebigen HTML-Daten",
  CMHTML_data_displayName: "HTML-Daten",
  CMHTML_data_description: "HTML-Daten",
  CMImage_displayName: "Technisches Bild",
  CMImage_description: "Ein technisches Bild ohne redaktionelle Daten",
  CMImage_data_displayName: "Bilddaten",
  CMImage_data_description: "Bilddaten",
  CMImage_description_displayName: "Beschreibung",
  CMImage_description_description: "Beschreibungstext",
  CMImage_description_emptyText: "Geben Sie hier den Beschreibungstext ein.",
  CMImageMap_pictures_displayName: "Bild",
  CMImageMap_localSettings_overlay_displayTitle_displayName: "Zeige Titel/Name",
  CMImageMap_localSettings_overlay_displayShortText_displayName: "Zeige Kurzbeschreibung",
  CMImageMap_localSettings_overlay_displayPicture_displayName: "Zeige Bild",
  CMInteractive_displayName: "Interaktiv",
  CMInteractive_description: "Objekt mit interaktiven Inhalten",
  CMInteractive_dataUrl_displayName: "Daten-URL (optional)",
  CMInteractive_dataUrl_description: "URL für das interaktive Objekt",
  CMInteractive_dataUrl_emptyText: "Geben Sie hier die URL für das interaktive Objekt ein.",
  CMLinkable_displayName: "Verlinkbares Objekt",
  CMLinkable_description: "Ein Objekt, das verlinkt werden kann und eine Segment-basierte URI hat.",
  CMLinkable_keywords_displayName: "Freie Schlagworte",
  CMLinkable_keywords_description: "Freie Schlagworte z. B. für SEO Optimierungen",
  CMLinkable_keywords_emptyText: "Geben Sie hier die freien Schlagworte ein.",
  CMLinkable_linkedSettings_displayName: "Verlinkte Einstellungen",
  CMLinkable_linkedSettings_description: "Verlinkte Einstellungen",
  CMLinkable_linkedSettings_emptyText: "Ziehen Sie Einstellungen aus der Bibliothek hierher.",
  CMLinkable_localSettings_displayName: "Lokale Einstellungen",
  CMLinkable_localSettings_description: "Lokale Einstellungen",
  CMLinkable_localSettings_emptyText: "Fügen Sie hier Struct XML ein.",
  CMLinkable_locationTaxonomy_displayName: "Orte",
  CMLinkable_locationTaxonomy_description: "Orte",
  CMLinkable_locationTaxonomy_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  CMLinkable_segment_displayName: "URL-Segment",
  CMLinkable_segment_description: "URL Segment, das in Links auf den Inhalt benutzt werden soll. Wenn dieser nicht gesetzt ist, wird der Inhaltsname verwendet.",
  CMLinkable_segment_emptyText: "Geben Sie hier das URL-Segment ein.",
  CMLinkable_subjectTaxonomy_displayName: "Themen",
  CMLinkable_subjectTaxonomy_description: "Themen",
  CMLinkable_subjectTaxonomy_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  CMLinkable_title_displayName: "Titel",
  CMLinkable_title_description: "Titel",
  CMLinkable_title_emptyText: "Geben Sie hier den Titel ein.",
  CMLinkable_validFrom_displayName: "Gültig ab",
  CMLinkable_validFrom_description: "Zeitpunkt des Beginns der Gültigkeit",
  CMLinkable_validFrom_emptyText: "Gültig ab",
  CMLinkable_validTo_displayName: "Gültig bis",
  CMLinkable_validTo_description: "Zeitpunkt des Endes der Gültigkeit",
  CMLinkable_validTo_emptyText: "Gültig bis",
  CMLinkable_viewtype_displayName: "Anzeigevariante",
  CMLinkable_viewtype_description: "Anzeigevariante ist eine spezielle Ansicht, die vom Standard abweicht.",
  CMLinkable_viewtype_emptyText: "Standard-Anzeigevariante",
  CMLinkable_extDisplayedDate_displayName: "Angezeigtes Datum",
  CMLinkable_htmlTitle_displayName: "HTML Titel",
  CMLinkable_htmlTitle_description: "HTML Titel für den HTML Head Bereich",
  CMLinkable_htmlTitle_emptyText: "Geben Sie hier den HTML Titel ein.",
  CMLinkable_htmlDescription_displayName: "HTML Meta-Beschreibung",
  CMLinkable_htmlDescription_description: "HTML Meta Tag Beschreibung für den HTML Head Bereich",
  CMLinkable_htmlDescription_emptyText: "Geben Sie hier die HTML Meta-Beschreibung ein.",
  CMLocalized_displayName: "Lokalisierbares CoreMedia-Blueprint-Objekt",
  CMLocalized_description: "Lokalisierbares CoreMedia-Blueprint-Objekt",
  CMLocalized_locale_displayName: "Locale",
  CMLocalized_locale_description: "Locale des Inhalts (Sprache, optional mit Land und Varianten)",
  CMLocalized_locale_emptyText: "Geben Sie hier die Locale des Inhalts ein.",
  CMLocalized_master_displayName: "Master",
  CMLocalized_master_description: "Master-Inhalt, von dem dieser Inhalt erzeugt wurde",
  CMLocalized_masterVersion_displayName: "Version des Masters",
  CMLocalized_masterVersion_description: "Version des Masters, von dem dieser Inhalt erzeugt wurde",
  CMLocalized_masterVersion_emptyText: "Geben Sie hier die Version des Master-Inhalts ein.",
  CMLocalized_ignoreUpdates_displayName: "Synchronisierung",
  CMLocalized_ignoreUpdates_description: "Diesen Inhalt weiterhin mit dem Master-Inhalt synchronisieren?",
  CMLocTaxonomy_displayName: "Orts-Schlagwort",
  CMLocTaxonomy_description: "Orts-Schlagwort",
  CMLocTaxonomy_latitudeLongitude_displayName: "Längen- und Breitengrad",
  CMLocTaxonomy_postcode_displayName: "Postleitzahl",
  CMLocTaxonomy_postcode_description: "Postleitzahl",
  CMLocTaxonomy_postcode_emptyText: "Geben Sie hier die Postleitzahl ein.",
  CMMail_displayName: "Mail",
  CMMail_description: "Mail",
  CMMedia_displayName: "Media",
  CMMedia_description: "Multimedia-Objekt",
  CMMedia_alt_displayName: "Alternativtext",
  CMMedia_alt_description: "Alternativer Text, der bei Darstellungsproblemen angezeigt wird.",
  CMMedia_alt_emptyText: "Geben Sie hier einen alternativen Text ein.",
  CMMedia_caption_displayName: "Beschriftung",
  CMMedia_caption_description: "Beschriftung des Multimedia-Objekts",
  CMMedia_copyright_displayName: "Urheberrecht",
  CMMedia_copyright_description: "Hinweis zum Urheberrecht (Copyright)",
  CMMedia_copyright_emptyText: "Geben Sie hier einen Hinweis zum Urheberrecht (Copyright) ein.",
  CMMedia_localSettings_playerSettings_muted_displayName: "Stumm schalten",
  CMMedia_localSettings_playerSettings_loop_displayName: "Wiederholen",
  CMMedia_localSettings_playerSettings_autoplay_displayName: "Autoplay",
  CMMedia_localSettings_playerSettings_hideControls_displayName: "Bedienelemente ausblenden",
  CMNavigation_displayName: "Navigationsknoten",
  CMNavigation_description: "Navigationsknoten",
  CMNavigation_children_displayName: "Navigationsunterknoten",
  CMNavigation_children_description: "Navigationsunterknoten",
  CMNavigation_css_displayName: "Benötigte CSS-Dateien",
  CMNavigation_css_description: "Benötigte CSS-Dateien, die zusätzlich geladen werden sollen",
  CMNavigation_css_emptyText: "Ziehen Sie eine CSS-Datei aus der Bibliothek hierher.",
  CMNavigation_hidden_displayName: "In Navigation und Sitemap ausblenden",
  CMNavigation_hidden_description: "Das Setzen dieser Eigenschaft blendet den Knoten in Navigation und Sitemap aus.",
  CMNavigation_hiddenInSitemap_displayName: "Nur in Sitemap ausblenden",
  CMNavigation_hiddenInSitemap_description: "Das Setzen dieser Eigenschaft blendet den Knoten in der Sitemap aus.",
  CMNavigation_javaScript_displayName: "Benötigte JavaScripts",
  CMNavigation_javaScript_description: "Benötigte JavaScripts, die zusätzlich geladen werden sollen",
  CMNavigation_javaScript_emptyText: "Ziehen Sie eine JavaScript-Datei aus der Bibliothek hierher.",
  CMNavigation_theme_displayName: "Theme",
  CMNavigation_theme_description: "Theme, das zum Rendern von HTML Seiten genommen wird",
  CMNavigation_theme_emptyText: "Ziehen Sie eine Theme-Datei aus der Bibliothek hierher.",
  CMObject_displayName: "CoreMedia-Blueprint-Objekt",
  CMObject_description: "CoreMedia-Blueprint-Objekt",
  CMPerson_displayName: "Person",
  CMPerson_description: "Person",
  CMPerson_firstName_displayName: "Vorname",
  CMPerson_firstName_description: "Vorname der Person",
  CMPerson_firstName_emptyText: "Geben Sie hier den Vornamen ein.",
  CMPerson_lastName_displayName: "Nachname",
  CMPerson_lastName_description: "Nachname der Person",
  CMPerson_lastName_emptyText: "Geben Sie hier den Nachnamen ein.",
  CMPerson_displayName_displayName: "Anzeigename",
  CMPerson_displayName_description: "Anzeigename der Person",
  CMPerson_displayName_emptyText: "Geben Sie hier den Anzeigenamen ein.",
  CMPerson_eMail_displayName: "E-Mail",
  CMPerson_eMail_description: "E-Mail Adresse der Person",
  CMPerson_eMail_emptyText: "Geben Sie hier die E-Mail Adresse der Person ein.",
  CMPerson_organization_displayName: "Unternehmen",
  CMPerson_organization_description: "Unternehmen der Person",
  CMPerson_organization_emptyText: "Geben Sie hier das Unternehmen der Person ein.",
  CMPerson_jobTitle_displayName: "Job-Titel",
  CMPerson_jobTitle_description: "Job-Titel der Person",
  CMPerson_jobTitle_emptyText: "Geben Sie hier den Job-Titel der Person ein.",
  CMPerson_teaserText_displayName: "Kurzbiografie",
  CMPerson_teaserText_description: "Kurzbiografie der Person",
  CMPerson_teaserText_emptyText: "Geben Sie hier die Kurzbiografie ein",
  CMPerson_detailText_displayName: "Biografie",
  CMPerson_detailText_description: "Biografie der Person",
  CMPerson_detailText_emptyText: "Geben Sie hier die Biografie ein.",
  CMPicture_displayName: "Bild",
  CMPicture_description: "Redaktionelles Bild",
  CMPicture_localSettings_disableCropping_displayName: "Originalbild benutzen",
  CMPicture_data_displayName: "Bild",
  CMPicture_data_description: "Binäre Bilddaten",
  CMPicture_title_displayName: "Bildtitel",
  CMPicture_title_description: "Titel des Bildes",
  CMPicture_title_emptyText: "Geben Sie hier den Bildtitel ein.",
  CMPicture_detailText_displayName: "Beschriftung",
  CMPicture_detailText_description: "Beschriftung des Bildes",
  CMPicture_detailText_emptyText: "Geben Sie hier die Beschriftung ein.",
  CMPlaceholder_displayName: "Platzhalter",
  CMPlaceholder_description: "Ein Inhalt, das einen Platzhalter repräsentiert",
  CMPlaceholder_id_displayName: "ID",
  CMPlaceholder_id_emptyText: "Geben Sie hier die ID des Platzhalters ein.",
  CMPlaceholder_viewtype_displayName: "Funktionsvariante",
  CMPlaceholder_viewtype_description: "Funktionsvariante ist eine spezielle Ansicht.",
  CMPlaceholder_viewtype_emptyText: "Ohne Funktion",
  Query_displayName: "Query",
  Query_description: "Query Dokument",
  CMQueryList_displayName: "Suchliste",
  CMQueryList_description: "Suchliste",
  CMQueryList_localSettings_limit_emptyText: "Anzahl eingeben",
  CMQueryList_localSettings_fq_documents_displayName: "Die Inhalte befinden sich in einem der Kontexte",
  CMQueryList_localSettings_fq_authors_displayName: "Die Inhalte haben einen der folgenden Autoren",
  CMQueryList_extendedItems_displayName: "Inhalte mit Festen Positionen",
  CMSettings_displayName: "Einstellungen",
  CMSettings_description: "Einstellungsinhalt",
  CMSettings_settings_displayName: "Einstellungen",
  CMSettings_settings_description: "Einstellungs-Struct",
  CMSettings_settings_emptyText: "Geben Sie hier Einstellungen als Struct-XML ein.",
  Preferences_displayName: "Einstellungen",
  EditorPreferences_displayName: "Benutzerprofil",
  EditorPreferences_data_description: "Benutzerprofil Einstellungen-Struct",
  EditorPreferences_data_emptyText: "Machen Sie hier Profileinstellungen für den Benutzer.",
  CMSite_displayName: "Site-Definition",
  CMSite_description: "Definition der Homepage, des Ordners und der Lokalisierung einer Site",
  CMSite_root_displayName: "Homepage",
  CMSite_root_description: "Homepage der Site",
  CMSite_id_displayName: "ID",
  CMSite_id_description: "Stabile ID der Site",
  CMSite_name_displayName: "Name",
  CMSite_name_description: "Der Name der Site",
  CMSite_name_emptyText: "Geben Sie hier den Namen der Site ein.",
  CMSite_locale_displayName: "Locale",
  CMSite_locale_description: "Sprache der Site, optional mit Land und Varianten",
  CMSite_locale_emptyText: "Geben Sie hier die Locale der Site ein.",
  CMSite_master_displayName: "Master",
  CMSite_master_description: "Master-Site, von der diese Site abgeleitet wurde",
  CMSite_siteManagerGroup_displayName: "Site-Manager-Gruppen",
  CMSite_siteManagerGroup_description: "Gruppen, welche für diese Site zuständig sind, separiert mit Kommas.",
  CMSite_siteManagerGroup_emptyText: "Geben Sie hier den Namen der für diese Site zuständigen Benutzergruppen an.",
  CMSitemap_displayName: "Sitemap",
  CMSitemap_description: "Ein Inhalt, welcher eine Sitemap repräsentiert",
  CMSitemap_root_displayName: "Wurzelseite",
  CMSitemap_root_description: "Die Seite ist die Wurzel der zu generierenden Sitemap.",
  CMSitemap_title_displayName: "Sitemap Titel",
  CMSitemap_title_description: "Titel der Sitemap",
  CMSitemap_title_emptyText: "Geben Sie hier den Sitemap Titel ein.",
  CMSymbol_displayName: "Symbol",
  CMSymbol_description: "Symbol mit einem festgelegten bekannten Namen als Wert",
  CMSymbol_description_displayName: "Beschreibung",
  CMSymbol_description_description: "Textuelle Beschreibung des Symbols",
  CMSymbol_description_emptyText: "Geben Sie hier die Beschreibung ein.",
  CMSymbol_icon_displayName: "Bild",
  CMSymbol_icon_description: "Ein Bild für das Symbol",
  CMTaxonomy_displayName: "Schlagwort",
  CMTaxonomy_description: "Schlagworte",
  CMTaxonomy_children_displayName: "Untergeordnete Schlagworte",
  CMTaxonomy_children_description: "Untergeordnete Schlagworte",
  CMTaxonomy_externalReference_displayName: "Externe Referenz",
  CMTaxonomy_externalReference_description: "Externe Referenz",
  CMTaxonomy_externalReference_emptyText: "Geben Sie hier eine externe Referenz ein.",
  CMTaxonomy_value_displayName: "Titel",
  CMTaxonomy_value_description: "Name des Schlagwortes",
  CMTaxonomy_value_emptyText: "Bitte geben Sie hier das Schlagwort ein.",
  CMTeasable_displayName: "Inhalt mit Teaser",
  CMTeasable_description: "Inhalt, der mit Hilfe von Teasern verlinkt werden kann.",
  CMTeasable_detailText_displayName: "Detailtext",
  CMTeasable_detailText_description: "Detailtext des Teasers",
  CMTeasable_detailText_emptyText: "Geben Sie hier den Detailtext des Teasers ein.",
  CMTeasable_notSearchable_displayName: "Von der Suche und der XML-Sitemap ausschließen",
  CMTeasable_pictures_displayName: "Bilder und andere Medien",
  CMTeasable_pictures_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  CMTeasable_related_displayName: "Verwandter Inhalt",
  CMTeasable_related_description: "Verwandter Inhalt",
  CMTeasable_related_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  CMTeasable_teaserText_displayName: "Teaser-Text",
  CMTeasable_teaserText_description: "Teaser-Text",
  CMTeasable_teaserText_emptyText: "Geben Sie hier den Text des Teasers ein.",
  CMTeasable_teaserTitle_displayName: "Teaser-Titel",
  CMTeasable_teaserTitle_description: "Titel des Teasers",
  CMTeasable_teaserTitle_emptyText: "Geben Sie hier den Teaser-Titel ein.",
  CMTeasable_authors_displayName: "Autoren",
  CMTeasable_localSettings_teaserSettings_renderLinkToDetailPage_displayName: "Link zur Detail-Seite rendern",
  CMTeaser_displayName: "Teaser",
  CMTeaser_description: "Teaser",
  CMTeaser_target_displayName: "Teaser-Ziel",
  CMTeaser_target_description: "Ziel, zu dem der Teaser verlinkt",
  CMTeaser_targets_displayName: "Teaser-Ziele",
  CMVideo_displayName: "Video",
  CMVideo_description: "Video",
  CMVideo_data_displayName: "Video Datei",
  CMVideo_dataUrl_displayName: "Video-URL",
  CMVideo_dataUrl_description: "URL des Videos",
  CMVideo_dataUrl_emptyText: "Geben Sie hier die Video-URL ein.",
  CMVideo_title_displayName: "Video-Titel",
  CMVideo_title_description: "Titel des Videos",
  CMVideo_title_emptyText: "Geben Sie hier den Videotitel ein.",
  CMVideo_detailText_displayName: "Video-Text",
  CMVideo_timeLine_displayName: "Zeitlinie",
  CMVideo_timeLine_defaultTarget_displayName: "Standardprodukt",
  CMViewtype_displayName: "Anzeigevariante",
  CMViewtype_description: "Ein Symbol für Anzeigevarianten",
  CMViewtype_layout_displayName: "Anzeigevariante",
  CMViewtype_layout_description: "Name der Anzeigevariante",
  CMViewtype_layout_emptyText: "Geben Sie hier den Namen der Anzeigevariante ein.",
  CMTheme_displayName: "Theme",
  CMTheme_description: "A theme defines the look and feels of a rendered website",
  CMTheme_resourceBundles_displayName: "Resource Bundles",
  CMTheme_resourceBundles_description: "Die resource bundles des Themes.",
  CMTheme_templateSets_displayName: "Template Sets",
  CMTheme_templateSets_description: "Die template sets des Themes.",
  CMTheme_javaScriptLibs_displayName: "Externe JavaScript Bibliotheken",
  CMTheme_javaScriptLibs_description: "Externe JavaScripte, die geladen werden sollen (werden vor den Theme-spezifischen JavaScripten geladen).",
  CMTheme_javaScripts_displayName: "Theme-spezifische JavaScripte",
  CMTheme_javaScripts_description: "Theme-spezifischen JavaScripte (werden nach den externen JavaScripten geladen).",
  CMTheme_css_displayName: "Benötigte CSS-Dateien",
  CMTheme_css_description: "Benötigte CSS-Dateien, die zusätzlich geladen werden sollen",
  CMTheme_viewRepositoryName_displayName: "View Repository Name",
  CMTheme_viewRepositoryName_description: "View repository Name für dieses Theme.",
  CMTheme_viewRepositoryName_emptyText: "Geben Sie hier den View Repository Namen ein.",
  CMTheme_icon_displayName: "Vorschaubild",
  CMTheme_icon_description: "Ein Vorschaubild für das Theme",
  CMTheme_description_displayName: "Kurzbeschreibung",
  CMTheme_description_description: "Kurzbeschreibung",
  CMTheme_description_emptyText: "Geben Sie hier die Kurzbeschreibung ein.",
  CMTheme_detailText_displayName: "Detailbeschreibung",
  CMTheme_detailText_description: "Detailbeschreibung dieses Themes",
  CMTheme_detailText_emptyText: "Geben Sie hier die Detailbeschreibung ein.",
  CMResourceBundle_localizations_displayName: "Lokalisierungen",
  CMResourceBundle_localizations_description: "Lokalisierungen",
  CMResourceBundle_localizations_emptyText: "Geben Sie hier die Lokalisierungen ein.",
  CMVisual_displayName: "Visual",
  CMVisual_description: "Objekt mit visuellen Inhalten",
  CMVisual_dataUrl_displayName: "Daten-URL (optional)",
  CMVisual_dataUrl_description: "URL für das Visual-Objekt",
  CMVisual_dataUrl_emptyText: "Geben Sie hier die URL für das Visual-Objekt ein.",
  CMVisual_height_displayName: "Höhe",
  CMVisual_height_description: "Höhe der Darstellung in Pixel",
  CMVisual_height_emptyText: "Geben Sie hier die Höhe in Pixel ein.",
  CMVisual_width_displayName: "Breite",
  CMVisual_width_description: "Breite der Darstellung in Pixel",
  CMVisual_width_emptyText: "Geben Sie hier die Breite in Pixel ein.",
  CMTemplateSet_description_displayName: "Beschreibung",
  CMTemplateSet_description_description: "Beschreibung",
  CMTemplateSet_description_emptyText: "Geben Sie hier eine Beschreibung ein.",
  CMTemplateSet_archive_displayName: "Template-Archiv",
  CMTemplateSet_archive_description: "Template-Archiv (jar oder zip)",
});
