import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import AMDocumentTypes_properties from "./AMDocumentTypes_properties";

/**
 * Overrides of ResourceBundle "AMDocumentTypes" for Locale "de".
 * @see AMDocumentTypes_properties#INSTANCE
 */
ResourceBundleUtil.override(AMDocumentTypes_properties, {
  AMAsset_text: "Asset",
  AMAsset_toolTip: "Basistyp für Assets",
  AMAsset_original_text: "Original",
  AMAsset_original_toolTip: "Originales Asset in bearbeitbarer Form",
  AMAsset_thumbnail_text: "Vorschau",
  AMAsset_thumbnail_toolTip: "Eine Vorschau des Assets",
  "AMAsset_metadata.copyright_text": "Copyright",
  "AMAsset_metadata.copyright_toolTip": "Informationen zu Autor und Copyright",
  "AMAsset_metadata.copyright_emptyText": "Geben Sie hier Informationen zu Autor und Copyright ein",
  "AMAsset_metadata.expirationDate_text": "Ablaufdatum",
  "AMAsset_metadata.expirationDate_emptyText": "Läuft nicht ab",
  "AMAsset_metadata.channels_text": "Kanäle",
  "AMAsset_metadata.regions_text": "Regionen",
  AMAsset_keywords_text: "Freie Schlagworte",
  AMAsset_keywords_toolTip: "Geben Sie hier die freien Schlagworte ein.",
  AMAsset_keywords_emptyText: "Freie Schlagworte z. B. für SEO Optimierungen",
  AMAsset_locationTaxonomy_text: "Orte",
  AMAsset_locationTaxonomy_toolTip: "Orte",
  AMAsset_locationTaxonomy_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  AMAsset_subjectTaxonomy_text: "Themen",
  AMAsset_subjectTaxonomy_toolTip: "Themen",
  AMAsset_subjectTaxonomy_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  AMAsset_assetTaxonomy_text: "Asset Kategorie",
  AMAsset_assetTaxonomy_toolTip: "Asset Kategorie",
  AMAsset_assetTaxonomy_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  AMPictureAsset_text: "Bild-Asset",
  AMPictureAsset_toolTip: "Ein Bild-Asset",
  AMPictureAsset_web_text: "Web-Rendition",
  AMPictureAsset_web_toolTip: "Eine Rendition zum Einbinden in Webseiten",
  AMPictureAsset_print_text: "Print-Rendition",
  AMPictureAsset_print_toolTip: "Eine Rendition zum Einbinden in Druckerzeugnisse",
  AMVideoAsset_text: "Video-Asset",
  AMVideoAsset_toolTip: "Ein Video-Asset",
  AMVideoAsset_web_text: "Web-Rendition",
  AMVideoAsset_web_toolTip: "Eine Rendition zum Einbinden in Webseiten",
  AMDocumentAsset_text: "Dokument-Asset",
  AMDocumentAsset_toolTip: "Ein Dokument-Asset",
  AMDocumentAsset_download_text: "Download-Rendition",
  AMDocumentAsset_download_toolTip: "Eine Rendition für den Download eines Dokumentes",
  AMTaxonomy_text: "Asset-Kategorie",
  AMTaxonomy_toolTip: "Kategorie für Asset-Dokumente",
  AMTaxonomy_value_text: "Name",
  AMTaxonomy_value_toolTip: "Name der Kategorie",
  AMTaxonomy_value_emptyText: "Bitte geben Sie hier den Namen der Kategorie ein.",
  AMTaxonomy_assetThumbnail_label: "Asset für Vorschaubild",
  AMTaxonomy_assetThumbnail_emptyText: "Ziehen Sie ein Asset für ein Vorschaubild aus der Bibliothek hierher.",
  CMPicture_asset_text: "Asset",
  CMPicture_asset_tooltip: "Das Asset von dem dieses Bild abgeleitet wurde",
});
