import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import CatalogStudioPlugin_properties from "./CatalogStudioPlugin_properties";

/**
 * Overrides of ResourceBundle "CatalogStudioPlugin" for Locale "de".
 * @see CatalogStudioPlugin_properties#INSTANCE
 */
ResourceBundleUtil.override(CatalogStudioPlugin_properties, {
  CMProduct_text: "Produkt",
  CMProduct_productName_text: "Produktname",
  CMProduct_productName_emptyText: "Geben Sie hier den Titel des Produktes ein.",
  CMProduct_productName_toolTip: "Titel des Produktes",
  CMProduct_productCode_text: "Produktcode",
  CMProduct_productCode_emptyText: "Geben Sie hier den Produktcode ein.",
  CMProduct_teaserText_text: "Kurzbeschreibung",
  CMProduct_teaserText_emptyText: "Geben Sie hier die Kurzbeschreibung des Produktes ein.",
  CMProduct_teaserText_toolTip: "Kurzbeschreibung des Produktes",
  CMProduct_detailText_text: "Detaillierte Beschreibung",
  CMProduct_detailText_emptyText: "Geben Sie hier die ausführliche Beschreibung des Produktes ein.",
  CMProduct_detailText_toolTip: "Detaillierte Beschreibung des Produktes",
  CMProduct_downloads_text: "Downloads",
  CMProduct_downloads_emptyText: "Ziehen Sie Downloads aus der Bibliothek hierher.",
  CMProduct_downloads_toolTip: "Downloads zum Produkt",
  CMProduct_shortDescription_emptyText: "Geben Sie hier eine Kurzbeschreibung des Produktes ein.",
  CMProduct_shortDescription_text: "Kurzbeschreibung",
  CMProduct_shortDescription_toolTip: "Kurzbeschreibung des Produktes",
  CMProduct_longDescription_text: "Detaillierte Beschreibung",
  CMProduct_longDescription_emptyText: "Geben Sie hier die ausführliche Beschreibung des Produktes ein.",
  CMProduct_longDescription_toolTip: "Detaillierte Beschreibung des Produktes",
  CMProduct_contexts_text: "Kategorien",
  CMProduct_contexts_emptyText: "Ziehen Sie Produktkategorien aus der Bibliothek hierher.",
  CMProduct_contexts_toolTip: "Produktkategorien",
  CMProduct_parentChannel_text: "Übergeordnete Kategorien",
  CMProduct_parentChannel_emptyText: "Ziehen Sie Kategorien aus der Bibliothek hierher.",
  CMCategory_text: "Kategorie",
  CMCategory_products_text: "Produkte",
  CMCategory_title_text: "Kategoriename",
  CMCategory_title_emptyText: "Geben Sie hier den Namen der Kategorie ein.",
  CMCategory_title_toolTip: "Der Name der Kategorie",
  CMCategory_categoryName_text: "Kategoriename",
  CMCategory_categoryName_emptyText: "Geben Sie hier den Namen der Kategorie ein.",
  CMCategory_displayName_text: "Angezeigter Name",
  CMCategory_teaserText_text: "Kurzbeschreibung",
  CMCategory_teaserText_emptyText: "Geben Sie hier die Kurzbeschreibung an.",
  CMCategory_shortDescription_text: "Kurzbeschreibung",
  CMCategory_shortDescription_emptyText: "Geben Sie hier die Kurzbeschreibung an.",
  CMCategory_detailText_text: "Detaillierte Beschreibung",
  CMCategory_detailText_emptyText: "Geben Sie hier die ausführliche Beschreibung des Produktes ein.",
  CMCategory_parentChannel_text: "Übergeordnete Kategorie",
  CMCategory_parentChannel_emptyText: "Ziehen Sie eine Kategorie aus der Bibliothek hierher.",
  Catalog_show_all: "Beliebig",
  CMCategory_no_products_for_picture: "Dieses Bild ist keinem Produkt zugeordnet.",
  CMCategory_no_parent: "Diese Kategorie ist eine Oberkategorie und hat keine übergeordnete Kategorie.",
  CMCategory_no_products: "Diese Kategorie hat keine Produkte.",
  Tab_catalog_structure_title: "Katalog-Struktur",
  Corporate_catalog_title: "Katalog",
  ProductAssets_Downloads_label: "Downloads",
  PropertyGroup_Assets_label: "Assets",
  PropertyGroup_SubCategories_label: "Unterkategorien",
  PropertyGroup_RelatedProducts_label: "Verwandte Produkte",
  Catalog_show_search_fails_for_Content: "Der ausgewählte Inhalt kann in der Bibliothek mit den aktuellen Einstellungen nicht angezeigt werden. Ändern sie die präferierte Site in den Einstellungen, um den Inhalt anzuzeigen.",
  catalog_checkout_error_title: "Fehler bei der Bearbeitung des Katalogs",
  catalog_checkout_error_message: "Die Aktion konnte nicht ausgeführt werden, da {0} '{1}' von einem anderen Benutzer verwendet wird.",
  catalog_copy_or_link_title: "Kopieren",
  catalog_copy_or_link_message: "Should the items be linked into the category? (yes=link, no=copy)",
  catalog_undelete_err_title: "Fehler beim Wiederherstellen",
  catalog_undelete_err_message: "Die Verlinkung für '{0}' konnte nicht wiederhergestellt werden. Das Dokument wurde geöffnet so dass die Verlinkung manuell wiederhergestellt werden kann.",
  Filter_LostAndFound_text: "Verwaiste Katalogeinträge",
  Filter_LostAndFound_checkbox: "Nur verwaiste Katalogeinträge anzeigen",
  catalog_lists_product_code_column: "Produktcode",
});
