import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import Placements_properties from "./Placements_properties";

ResourceBundleUtil.override(Placements_properties, {
  "CMChannel_placement-main_text": "Hauptbereich",
  "CMChannel_placement-main_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-header_text": "Header",
  "CMChannel_placement-header_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-footer_text": "Footer",
  "CMChannel_placement-footer_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-footer-navigation_text": "Footer Navigation",
  "CMChannel_placement-footer-navigation_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-sidebar_text": "Seitenleiste",
  "CMChannel_placement-sidebar_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-tab_text": "Tab",
  "CMChannel_placement-tab_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-banner_text": "Banner",
  "CMChannel_placement-banner_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-additional_text": "Ergänzend",
  "CMChannel_placement-additional_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-header-advertisement_text": "Header Werbung",
  "CMChannel_placement-header-advertisement_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-footer-advertisement_text": "Footer Werbung",
  "CMChannel_placement-footer-advertisement_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-navigationBar_text": "Navigationsleiste",
  "CMChannel_placement-navigationBar_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-secondaryNav_text": "Zweite Navigationsleiste",
  "CMChannel_placement-secondaryNav_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-footerSecondaryNav_text": "Untere Navigationsleiste",
  "CMChannel_placement-footerSecondaryNav_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-topTeaser_text": "Teaser",
  "CMChannel_placement-topTeaser_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-hero_text": "Hero Bereich",
  "CMChannel_placement-hero_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-placement1_text": "Bereich 1",
  "CMChannel_placement-placement1_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-placement2_text": "Bereich 2",
  "CMChannel_placement-placement2_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-placement3_text": "Bereich 3",
  "CMChannel_placement-placement3_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-placement4_text": "Bereich 4",
  "CMChannel_placement-placement4_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-above_text": "Oberhalb Hauptbereich",
  "CMChannel_placement-above_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-below_text": "Unterhalb Hauptbereich",
  "CMChannel_placement-below_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMChannel_placement-product-detail_text": "Produkt Details",
  "CMChannel_placement-product-detail_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
});
