import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import Placements_properties from "./Placements_properties";

ResourceBundleUtil.override(Placements_properties, {
  "CMChannel_placement-main_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-header_text": "ヘッダー",
  "CMChannel_placement-header_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-footer_text": "フッター",
  "CMChannel_placement-footer_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-sidebar_text": "サイドバー",
  "CMChannel_placement-sidebar_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-tab_text": "タブ",
  "CMChannel_placement-tab_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-banner_text": "バナー",
  "CMChannel_placement-banner_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-additional_text": "追加の",
  "CMChannel_placement-additional_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-header-advertisement_text": "ヘッダー広告",
  "CMChannel_placement-header-advertisement_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-footer-advertisement_text": "フッター広告",
  "CMChannel_placement-footer-advertisement_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-navigationBar_text": "ナビゲーションバー",
  "CMChannel_placement-navigationBar_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-secondaryNav_text": "セカンダリナビゲーション",
  "CMChannel_placement-footerSecondaryNav_text": "セカンダリナビゲーションのフッター",
  "CMChannel_placement-topTeaser_text": "トップティーザー",
  "CMChannel_placement-topTeaser_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-hero_text": "スーパーヒーロー",
  "CMChannel_placement-hero_emptyText": "ライブラリから要素をドラッグして追加します。",
  "CMChannel_placement-placement1_text": "配置1",
  "CMChannel_placement-placement1_emptyText": "ライブラリから要素をドラッグして追加します。",
  "CMChannel_placement-placement2_text": "配置2",
  "CMChannel_placement-placement2_emptyText": "ライブラリから要素をドラッグして追加します。",
  "CMChannel_placement-placement3_text": "配置3",
  "CMChannel_placement-placement3_emptyText": "ライブラリから要素をドラッグして追加します。",
  "CMChannel_placement-placement4_text": "配置4",
  "CMChannel_placement-placement4_emptyText": "ライブラリから要素をドラッグして追加します。",
  "CMChannel_placement-above_text": "メイン上記",
  "CMChannel_placement-above_emptyText": "ライブラリから要素をドラッグして追加します。",
  "CMChannel_placement-below_text": "メインの下に",
  "CMChannel_placement-below_emptyText": "ライブラリから要素をドラッグして追加します。",
  "CMChannel_placement-footerSecondaryNav_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
  "CMChannel_placement-secondaryNav_emptyText": "こちらのライブラリからドラッグしてコンテンツを追加。",
});
