import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import ElasticSocialStudioPlugin_properties from "./ElasticSocialStudioPlugin_properties";

/**
 * Overrides of ResourceBundle "ElasticSocialStudioPlugin" for Locale "de".
 * @see ElasticSocialStudioPlugin_properties#INSTANCE
 */
ResourceBundleUtil.override(ElasticSocialStudioPlugin_properties, {
  CMMail_text: "E-Mail Vorlage",
  CMMail_from_text: "Von",
  CMMail_from_emptyText: "Geben Sie hier die E-Mail-Adresse des Senders ein.",
  CMMail_subject_text: "Betreff",
  CMMail_subject_emptyText: "Geben Sie hier den Betreff der E-Mail an.",
  CMMail_text_text: "E-Mail Text",
  CMMail_text_emptyText: " ",
  CMMail_contentType_text: "Content-Type (text/plain, text/html)",
  CMMail_contentType_emptyText: "text/plain, text/html",
  CMMail_lang_text: "Sprache",
  CMMail_lang_emptyText: "Geben Sie hier die Sprache ein.",
  CMMail_country_text: "Land",
  CMMail_country_emptyText: "Geben Sie hier das Land ein.",
  CMMail_variants_text: "Variante",
  CMMail_variants_emptyText: "Geben Sie hier die Variante ein.",
  ESDynamicList_text: "Dynamische Liste aus Elastic Social",
  ESDynamicList_interval_text: "Intervall",
  ESDynamicList_aggregationType_text: "Art der Liste",
  ESDynamicList_channel_text: "Kontext",
  cmmail_help_text: "Hilfe zum E-Mail-Formular anzeigen",
  cmmail_help_window_title: "Hilfe zum E-Mail-Formular",
  cmmail_help_window_content: "Im E-Mail-Formular können Sie den Text bestimmen, den ein Benutzer in einer E-Mail angezeigt bekommt. Dabei können Sie Werte setzen, die dann je nach Nutzer dynamisch generiert werden. Dazu gehören:",
  cmmail_help_window_value: "Wert",
  cmmail_help_window_description: "Beschreibung",
  cmmail_help_window_value_name: "Hier wird automatisch der Name des Nutzers eingefügt.",
  cmmail_help_window_value_givenName: "Hier wird automatisch der Vorname des Nutzers eingefügt.",
  cmmail_help_window_value_surName: "Hier wird automatisch der Nachname des Nutzers eingefügt.",
  cmmail_help_window_value_email: "Hier wird automatisch die E-Mail Adresse des Nutzers eingefügt.",
  cmmail_help_window_value_token: "Hier wird automatisch ein Sicherheitsmerkmal eingefügt.",
  cmmail_help_window_value_baseUrl: "Hier wird automatisch ein Aktivierungs- oder Passwort-Zurücksetzen-Link eingefügt.",
  cmmail_help_window_value_commentText: "Hier wird automatisch der Kommentar des Nutzers eingefügt (falls möglich).",
  cmmail_help_window_value_commentDate: "Hier wird automatisch das Datum des Kommentars des Nutzers eingefügt (falls möglich).",
  cmmail_help_window_value_commentUrl: "Hier wird automatisch die URL des Artikel der kommentiert wurde eingefügt (falls möglich).",
  cmmail_help_window_value_replyText: "Hier wird automatisch die Antwort des Nutzers eingefügt (falls möglich).",
  cmmail_help_window_value_replyAuthorName: "Hier wird automatisch der Names des Nutzers eingefügt, der geantwortet hat (falls möglich).",
  cmmail_help_window_value_replyDate: "Hier wird automatisch das Datum der Antwort des Nutzers eingefügt (falls möglich).",
  curated_content_create_article_button_tooltip: "Neuen Artikel aus Kommentartexten der ausgewählten Beiträge anlegen",
  curated_content_create_pictures_button_tooltip: "Bilder aus Medien der ausgewählten Beiträge anlegen",
  curated_content_create_gallery_button_tooltip: "Bildergalerie aus Medien der ausgewählten Beiträge anlegen",
  btn_close: "Schließen",
  MOST_COMMENTED: "Meist kommentierte",
  MOST_RATED: "Mit den meisten Bewertung",
  MOST_LIKED: "Mit den meisten Empfehlungen",
  MOST_SHARED: "Mit den meisten Shares",
  TOP_RATED: "Mit der besten Bewertung",
  TOP_REVIEWED: "Mit der besten Review Bewertung",
  MOST_REVIEWED: "Mit den meisten Reviews",
  INFINITY: "Alle",
  LAST_YEAR: "Vom letzten Jahr",
  LAST_MONTH: "Vom letzten Monat",
  LAST_WEEK: "Von der letzten Woche",
  LAST_DAY: "Vom letzten Tag",
});
