import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import LcDocTypes_properties from "./LcDocTypes_properties";

/**
 * Overrides of ResourceBundle "LcDocTypes_properties" for locale "de".
 * @see LcDocTypes_properties
 */
ResourceBundleUtil.override(LcDocTypes_properties, {
  CMMarketingSpot_displayName: "e-Marketing Spot",
  CMMarketingSpot_externalId_displayName: "e-Marketing Spot",
  CMMarketingSpot_externalId_emptyText: "Ziehen Sie einen e-Marketing Spot aus der Bibliothek hierher.",
  CMProductTeaser_displayName: "Produktteaser",
  CMProductTeaser_externalId_displayName: "Produkt",
  CMProductTeaser_externalId_emptyText: "Ziehen Sie ein Produkt aus der Bibliothek hierher.",
  CMProductTeaser_pictures_displayName: "Angepasstes Teaserbild",
  CMProductTeaser_localSettings_shopNow_displayName: "Warenkorb Funktionalität für Produktteaser",
  CMProductList_displayName: "Produktliste",
  CMProductList_externalId_displayName: "Produktkategorie",
  CMProductList_externalId_emptyText: "Ziehen Sie eine Kategorie aus der Bibliothek hierher.",
  CMProductList_items_displayName: "Top Inhalte",
  CMProductList_localSettings_productList_displayName: "Suchfilter",
  CMProductList_localSettings_productList_orderBy_displayName: "In welcher Reihenfolge sollen die Produkte sortiert werden?",
  CMProductList_localSettings_productList_orderBy_emptyText: "Auswählen",
  CMProductList_localSettings_productList_orderBy_ORDER_BY_TYPE_BRAND_ASC_displayName: "Brands",
  CMProductList_localSettings_productList_orderBy_ORDER_BY_TYPE_CATEGORY_ASC_displayName: "Kategorien",
  CMProductList_localSettings_productList_orderBy_ORDER_BY_TYPE_PRICE_ASC_displayName: "Preis - Aufsteigend",
  CMProductList_localSettings_productList_orderBy_ORDER_BY_TYPE_PRICE_DSC_displayName: "Preis - Absteigend",
  CMProductList_localSettings_productList_orderBy_ORDER_BY_TYPE_NAME_ASC_displayName: "Name - Aufsteigend",
  CMProductList_localSettings_productList_orderBy_ORDER_BY_TYPE_NAME_DSC_displayName: "Name - Absteigend",
  CMProductList_localSettings_productList_orderBy_ORDER_BY_TYPE_RELEVANCE_displayName: "Relevanz",
  CMProductList_localSettings_productList_orderBy_ORDER_BY_TYPE_TOP_RATED_displayName: "Top Bewertet",
  CMProductList_localSettings_productList_offset_displayName: "Ab welcher Position in der Suchergebnisliste sollen die Produkte dargestellt werden?",
  CMProductList_localSettings_productList_offset_emptyText: "Auswählen",
  CMProductList_localSettings_productList_maxLength_displayName: "Wieviele Elemente sollen maximal dargestellt werden?",
  CMProductList_localSettings_productList_maxLength_emptyText: "Auswählen",
  CMChannel_localSettings_shopNow_displayName: "Warenkorb Funktionalität für Produktteaser",
  CMTeaser_localSettings_useTeaserTargetValidity_displayName: "Teaser nur anzeigen, wenn das Teaser-Ziel gültig ist",
  CMImageMap_localSettings_overlay_displayDefaultPrice_displayName: "Zeige Standardpreis",
  CMImageMap_localSettings_overlay_displayDiscountedPrice_displayName: "Zeige ermäßigten Preis",
  CMImageMap_localSettings_overlay_displayOutOfStockLink_displayName: "Zeige Verweis auf Out-Of-Stock Produktdetailseiten",
  CMImageMap_localSettings_overlay_hideOutOfStockProducts_displayName: "Verstecke alle Out-Of-Stock Produkte",
  Commerce_definingAttributes_emptyText: "Keine definierenden Attribute verfügbar.",
  Commerce_describingAttributes_emptyText: "Keine beschreibenden Attribute verfügbar.",
  Commerce_Product_listPrice_emptyText: "Kein Listenpreis verfügbar.",
  Commerce_Product_offerPrice_emptyText: "Kein Offerpreis verfügbar.",
  Commerce_Product_richMedia_emptyText: "Keine Bilder oder Medien verfügbar.",
  Commerce_Product_assetMgmt_inactive_displayName: "Das Asset Management ist fü die Bilder und anderen Medien des Produkts nicht aktiviert.",
  Commerce_Product_downloads_emptyText: "Keine Downloads verfügbar.",
  Commerce_Product_productVariants_emptyText: "Keine Produktvarianten verfügbar.",
  Commerce_Category_PropertyGroup_parentCategory_emptyText: "Dies ist eine Topkategorie und sie hat somit keine Überkategorie.",
  Commerce_Category_subcategories_emptyText: "Diese Kategorie hat keine Unterkategorien.",
  Commerce_Category_products_emptyText: "Diese Kategorie hat keine Produkte.",
  Product_Link_empty_displayName: "Ziehen Sie ein Produkt aus der Bibliothek hierher.",
  Product_augmentedMessage_displayName: "Das Produkt '{0}' ist nun augmentiert mit Content aus dem Repository. Das augmentierte Produkt wird nun angezeigt.",
  Category_Link_empty_displayName: "Ziehen Sie eine Kategorie aus der Bibliothek hierher.",
  Category_augmentedMessage_displayName: "Die Kategorie '{0}' ist nun augmentiert mit Content aus dem Repository. Die augmentierte Kategorie wird nun angezeigt.",
  MarketingSpot_Link_empty_displayName: "Ziehen Sie einen Marketing Spot aus der Bibliothek hierher.",
  CMExternalChannel_displayName: "Augmentierte Kategorie",
  CMExternalChannel_description: "Augmentierte Kategorie",
  CMExternalChannel_externalId_displayName: "Commerce-Referenz",
  CMExternalChannel_externalId_description: "Zeigt auf eine externe Kategorie",
  CMExternalChannel_pdpPagegrid_displayName: "Bereiche",
  CMExternalChannel_pdpPagegrid_placements_2_layout_displayName: "Layout",
  CMExternalProduct_displayName: "Augmentiertes Produkt",
  CMExternalProduct_description: "Augmentiertes Produkt",
  CMExternalProduct_externalId_displayName: "Commerce-Referenz",
  CMExternalProduct_externalId_description: "Zeigt auf ein externes Produkt",
  CMExternalProduct_pdpPagegrid_displayName: "Bereiche",
  CMExternalProduct_pdpPagegrid_placements_2_layout_displayName: "Layout",
  CMExternalPage_displayName: "Augmentierte Seite",
  CMExternalPage_description: "Augmentierte Seite",
  CMExternalPage_externalId_displayName: "Externe Seiten ID",
  CMExternalPage_externalId_emptyText: "Geben Sie die externe Seiten ID hier ein.",
  CMExternalPage_externalUriPath_displayName: "Externer URI Pfad",
  CMExternalPage_externalUriPath_emptyText: "Geben Sie den externen URI Pfad hier ein (inklusive Parameter).",
  CatalogView_invalid_store_displayName: "Bitte eine Site mit gültigem E-Commerce-Katalog auswählen.",
  CatalogView_empty_displayName: "Die Liste ist leer.",
  Catalog_DragDrop_multiSelect_displayName: "{0} ausgewählte Katalog-Einträge",
  HeaderToolbar_workspaceSelector_empty_displayName: "E-Commerce-Workspace auswählen.",
  p13n_commerce_user_segments_selector_emptyText: "E-Commerce-Benutzersegment auswählen.",
  p13n_commerce_user_segments_selector_for_persona_emptyText: "Ein E-Commerce-Benutzersegment zur Kundenpersona hinzufügen.",
  p13n_commerce_user_contracts_selector_emptyText: "E-Commerce-Benutzerkontrakt auswählen.",
  p13n_commerce_user_contracts_selector_for_persona_emptyText: "Ein E-Commerce-Benutzerkontrakt zur Kundenpersona hinzufügen.",
});
