import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import AmDocTypes_properties from "./AmDocTypes_properties";

/**
 * Overrides of ResourceBundle "AmDocTypes_properties" for locale "de".
 * @see AmDocTypes_properties
 */
ResourceBundleUtil.override(AmDocTypes_properties, {
  AMAsset_displayName: "Asset",
  AMAsset_description: "Basistyp für Assets",
  AMAsset_original_displayName: "Original",
  AMAsset_original_description: "Originales Asset in bearbeitbarer Form",
  AMAsset_thumbnail_displayName: "Vorschau",
  AMAsset_thumbnail_description: "Eine Vorschau des Assets",
  AMAsset_metadata_copyright_displayName: "Copyright",
  AMAsset_metadata_copyright_description: "Informationen zu Autor und Copyright",
  AMAsset_metadata_copyright_emptyText: "Geben Sie hier Informationen zu Autor und Copyright ein",
  AMAsset_metadata_expirationDate_displayName: "Ablaufdatum",
  AMAsset_metadata_expirationDate_emptyText: "Läuft nicht ab",
  AMAsset_metadata_channels_displayName: "Kanäle",
  AMAsset_metadata_regions_displayName: "Regionen",
  AMAsset_keywords_displayName: "Freie Schlagworte",
  AMAsset_keywords_description: "Geben Sie hier die freien Schlagworte ein.",
  AMAsset_keywords_emptyText: "Freie Schlagworte z. B. für SEO Optimierungen",
  AMAsset_locationTaxonomy_displayName: "Orte",
  AMAsset_locationTaxonomy_description: "Orte",
  AMAsset_locationTaxonomy_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  AMAsset_subjectTaxonomy_displayName: "Themen",
  AMAsset_subjectTaxonomy_description: "Themen",
  AMAsset_subjectTaxonomy_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  AMAsset_assetTaxonomy_displayName: "Asset Kategorie",
  AMAsset_assetTaxonomy_description: "Asset Kategorie",
  AMAsset_assetTaxonomy_emptyText: "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  AMPictureAsset_displayName: "Bild-Asset",
  AMPictureAsset_description: "Ein Bild-Asset",
  AMPictureAsset_web_displayName: "Web-Rendition",
  AMPictureAsset_web_description: "Eine Rendition zum Einbinden in Webseiten",
  AMPictureAsset_print_displayName: "Print-Rendition",
  AMPictureAsset_print_description: "Eine Rendition zum Einbinden in Druckerzeugnisse",
  AMVideoAsset_displayName: "Video-Asset",
  AMVideoAsset_description: "Ein Video-Asset",
  AMVideoAsset_web_displayName: "Web-Rendition",
  AMVideoAsset_web_description: "Eine Rendition zum Einbinden in Webseiten",
  AMDocumentAsset_displayName: "Dokument-Asset",
  AMDocumentAsset_description: "Ein Dokument-Asset",
  AMDocumentAsset_download_displayName: "Download-Rendition",
  AMDocumentAsset_download_description: "Eine Rendition für den Download eines Dokumentes",
  AMTaxonomy_displayName: "Asset-Kategorie",
  AMTaxonomy_description: "Kategorie für Asset-Dokumente",
  AMTaxonomy_value_displayName: "Name",
  AMTaxonomy_value_description: "Name der Kategorie",
  AMTaxonomy_value_emptyText: "Bitte geben Sie hier den Namen der Kategorie ein.",
  AMTaxonomy_assetThumbnail_emptyText: "Ziehen Sie ein Asset für ein Vorschaubild aus der Bibliothek hierher.",
  CMPicture_asset_displayName: "Asset",
});
