#!/bin/sh

echo "[DOCKER ENTRYPOINT] - entering $0"
set -e
if [ "${DEBUG_ENTRYPOINT}" = "true" ]; then
  echo "[DOCKER ENTRYPOINT] - DEBUG_ENTRYPOINT detected, all commands will be printed"
  set -x
fi

# do not remove '< /dev/null 2> /dev/null | grep -v groovy\:' - this ensures groovysh exit and only value printing
IMPORTED=$(./tools/bin/cm groovysh /coremedia/getSystemTableProperty.groovy -q -DpropKey=themes-imported < /dev/null 2> /dev/null | grep -v groovy\:)

echo "[DOCKER ENTRYPOINT] - importing themes from ${THEMES_ARCHIVE_URL}"
if [ "${IMPORTED}" != "true"  ] || [ "${FORCE_REIMPORT_THEMES}" = "true" ]; then
  ./tools/bin/cm import-themes -u "${TOOLS_USER}" -p "${TOOLS_PASSWORD}" "${THEMES_ARCHIVE_URL}" 2> /dev/null
  ./tools/bin/cm groovysh /coremedia/setSystemTableProperty.groovy -q -DpropKey=themes-imported -DpropVal=true < /dev/null 2> /dev/null
else
  echo "[DOCKER ENTRYPOINT] - themes already imported, skipping ..."
fi

test $# -gt 0 && exec ./$@ || echo "[DOCKER ENTRYPOINT] - entrypoint chain finished"
