import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import ECommerceStudioPlugin_properties from "./ECommerceStudioPlugin_properties";

/**
 * Overrides of ResourceBundle "ECommerceStudioPlugin" for Locale "de".
 * @see ECommerceStudioPlugin_properties#INSTANCE
 */
ResourceBundleUtil.override(ECommerceStudioPlugin_properties, {
  TreeView_catalog: "E-Commerce",
  Categorys_Products_Link_empty_text: "Ziehen Sie Kategorien oder Produkte aus der Bibliothek hierher.",
  CatalogView_invalid_store_text: "Bitte eine Site mit gültigem E-Commerce-Katalog auswählen.",
  CatalogView_empty_text: "Die Liste ist leer.",
  CatalogView_multiCatalog_emptySearch_text: "Kein Suchergebnis, möglicherweise weil die Suche auf den Katalog '{0}' beschränkt ist.\nSie können versuchen, in einem anderen Katalog zu suchen.",
  CatalogView_spots_selection_empty_text: "Keine e-Marketing Spots gefunden.",
  CatalogView_delete_button: "Eintrag löschen.",
  Catalog_DragDrop_multiSelect_text: "{0} ausgewählte Katalog-Einträge",
  Catalog_replace_reference_text: "Die aktuelle Referenz zu diesem Inhalt im Commerce-Katalog wird entfernt und kann im Anschluss neu von Ihnen ausgewählt werden.  <br/><br/> Bei jeder neuen Verwendung dieses Inhalts wird dann auf den neuen Inhalt im Commerce-Katalog verlinkt und referenziert. <br/><br/> Möchten Sie fortfahren?",
  Catalog_replace_reference_title: "Commerce-Referenz Ändern",
  Catalog_replace_reference_button: "Referenz Ändern",
  Catalog_replace_reference_button_confirm: "Ja, Referenz Ändern",
  Catalog_replace_reference_button_abort: "Abbrechen",
  id_header: "ID",
  catalog_header: "Katalog",
  description_header: "Beschreibung",
  CMAbstractCategory_text: "Allgemeine Kategorie",
  Category_label: "Kategorie",
  Product_label: "Produkt",
  ProductVariant_label: "Produktvariante",
  MarketingSpot_label: "e-Marketing Spot",
  Marketing_label: "e-Marketing Spots",
  CatalogTypeSelector_empty_text: "Katalog Typ…",
  StoreTree_marketing_root: "e-Marketing Spots",
  StoreTree_root_category: "Produktkatalog",
  commerceConnectionError_title: "Verbindungsfehler",
  commerceConnectionError_message: "Auf den Katalog kann nicht zugegriffen werden ('{0}'). Bitte kontaktieren Sie Ihren Systemadministrator, wenn dieses Problem fortlaufend auftritt.",
  commerceCatalogNotFoundError_title: "Konfigurationsfehler",
  commerceCatalogNotFoundError_message: "Auf den Katalog kann nicht zugegriffen werden ('{0}').",
  commerceCatalogItemNotFoundError_title: "Katalogfehler",
  commerceCatalogItemNotFoundError_message: "Katalogelement nicht gefunden ('{0}').",
  commerceCatalogError_title: "Katalogfehler",
  commerceCatalogError_message: "Ein Katalogfehler ist aufgetreten ('{0}'). Bitte kontaktieren Sie Ihren Systemadministrator, wenn dieses Problem fortlaufend auftritt.",
  commerceUnauthorizedError_title: "Authentisierungsfehler",
  commerceUnauthorizedError_message: "Die Authentisierung am Katalog ist fehlgeschlagen ('{0}'). Bitte kontaktieren Sie Ihren Systemadministrator, wenn dieses Problem fortlaufend auftritt.",
  commerceAugmentationError_title: "Fehler beim Augmentieren",
  commerceAugmentationError_message: "Das Layout konnte nicht initialisiert werden, da die Root-Kategorie noch nicht augmentiert ist. Bitte augmentieren Sie die Root-Kategorie zuerst.",
  CollectionView_catalogRepositoryToolbar_label: "Katalog Bibliothek",
  CollectionView_catalogSearchToolbar_label: "Katalog Suche",
  CollectionView_search_filter_combo_emptyText: "Filter hinzufügen",
  CollectionView_search_filter_resetAll_text: "Alle zurücksetzen",
  CollectionView_search_filter_empty_title: "Zu viele Ergebnisse?",
  CollectionView_search_filter_empty_text: "Beginnen Sie mit dem Hinzufügen von Filtern, um Ihre Suche zu verfeinern.",
  CollectionView_search_filter_empty_facet_text: "Auswählen",
  CollectionView_search_filter_allAdded_text: "Alle Filter wurden hinzugefügt",
  CollectionView_search_no_filter_empty_title: "Filtern nicht möglich",
  CollectionView_search_no_filter_empty_text: "In der aktuellen Kategorie sind keine Filter verfügbar",
  CollectionView_search_no_filter_allAdded_text: "Nicht verfügbar",
  saveSearch_invalidFacets_title: "Ungültiger Filter",
  saveSearch_invalidFacets_text: "Die gespeicherte Suche konnte nicht ausgeführt werden, da einige Filter ungültig sind. Um den Fehler zu beheben können Sie entweder die ungültigen Filter entfernen oder die gespeicherte Suche vollständig löschen.",
  saveSearch_invalidFacets_delete_btn_text: "Suche löschen",
  saveSearch_invalidFacets_clear_btn_text: "Ungültige Filter entfernen",
  saveSearch_invalidCategory_title: "Kategorie in aktueller Site nicht verfügbar",
  saveSearch_invalidCategory_text: "Diese Kategorie existiert nicht mehr. Wollen Sie \"{0}\" aus ihren Favoriten löschen?",
  saveSearch_invalidCategory_delete_btn_text: "Ja, löschen",
  commerceStoreItemNotFoundError_message: "Store konnte nicht initialisiert werden ('{0}').",
  Action_createCategory_text: "Kategorie anlegen",
  Action_createCategory_tooltip: "Kategorie anlegen",
  Action_createCategory_error_title: "Fehler beim Anlegen der Kategorie",
  Action_createCategory_error_message: "Die neue Kategorie konnte nicht angelegt werden. Die übergeordnete Kategorie '{0}' ist vom Benutzer '{1}' ausgeliehen.",
  Action_createCategory_error_general_message: "Die neue Kategorie konnte nicht angelegt werden. Die übergeordnete Kategorie '{0}' ist von einem anderen Benutzer ausgeliehen.",
  Action_createProduct_text: "Produkt anlegen",
  Action_createProduct_tooltip: "Produkt anlegen",
  Action_createProduct_error_title: "Fehler beim Anlegen des Produktes",
  Action_createProduct_error_message: "Das Produkt konnte nicht angelegt werden. Die übergeordnete Kategorie '{0}' ist vom Benutzer '{1}' ausgeliehen.",
  Action_createProduct_error_general_message: "Das Produkt konnte nicht angelegt werden. Die übergeordnete Kategorie '{0}' ist von einem anderen Benutzer ausgeliehen.",
  ContentValidator_CMProduct_productCode_RegExpValidator_text: "In diesem Feld sind Leerzeichen, '/' und ':' nicht erlaubt.",
  EcCatalogPreferences_tab_title: "Produkt-Katalog",
  EcCatalogPreferences_catalog_title: "Katalog",
  EcCatalogPreferences_show_catalog_items: "Zeige Produkte und Kategorien als Inhalte",
  EcCatalogPreferences_sort_children: "Kategorien nach Namen sortieren (wirkt sich negativ auf die Performance aus)",
  Catalog_show_in_tree_fails_title: "Inhalt kann in der Bibliothek nicht angezeigt werden",
  Catalog_show_in_content_tree_fails_for_Content: "Der ausgewählte Inhalt kann in der Bibliothek mit den aktuellen Einstellungen nicht angezeigt werden. Aktivieren Sie \"Produkte und Kategorien als Inhalt anzeigen\" in den Einstellungen, um den Inhalt anzuzeigen.",
  Catalog_show_in_catalog_tree_fails_for_Content: "Der ausgewählte Inhalt kann in der Bibliothek mit den aktuellen Einstellungen nicht angezeigt werden. Ändern sie die präferierte Site oder aktivieren Sie \"Produkte und Kategorien als Inhalt anzeigen\" in den Einstellungen, um den Inhalt anzuzeigen.",
  Catalog_show_preferences_button_text: "Einstellungen öffnen...",
  Catalog_show_switch_site_button_text: "Präferierte Site ändern",
  Catalog_show_in_catalog_tree_fails_for_CatalogObject: "Der ausgewählte Inhalt kann in der Bibliothek mit den aktuellen Einstellungen nicht angezeigt werden. Ändern sie die präferierte Site zu '{0}'.",
});
