import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import AlxWebtrendsDocTypes_properties from "./AlxWebtrendsDocTypes_properties";

/**
 * Overrides of ResourceBundle "AlxWebtrendsDocTypes_properties" for locale "ja".
 * @see AlxWebtrendsDocTypes_properties
 */
ResourceBundleUtil.override(AlxWebtrendsDocTypes_properties, {
  CMChannel_localSettings_webtrends_dcssip_displayName: "マルチサイト環境内のウェブサイトの名前",
  CMChannel_localSettings_webtrends_dcssip_emptyText: "ここにウェブサイトの名前を入力します。",
  CMChannel_localSettings_webtrends_dcsid_displayName: "Webtrends DCSID",
  CMChannel_localSettings_webtrends_dcsid_emptyText: "ここにWebtrendsのデータ収集識別子を入力します。",
  CMChannel_localSettings_webtrends_disabled_displayName: "トラッキングの無効化",
  CMChannel_localSettings_webtrends_disabled_true_displayName: "無効",
  CMChannel_localSettings_webtrends_homeUrl_displayName: "ホームURL",
  CMChannel_localSettings_webtrends_homeUrl_emptyText: "ここにWebtrendsのホームURLを入力します。",
  CMChannel_localSettings_webtrends_reportUrlPrefix_displayName: "レポートURLのプレフィックス",
  CMChannel_localSettings_webtrends_reportUrlPrefix_emptyText: "ここにレポートURLのプレフィックスを入力します。",
  CMChannel_localSettings_webtrends_spaceId_displayName: "スペースID",
  CMChannel_localSettings_webtrends_spaceId_emptyText: "ここにWebtrendsのスペースIDを入力します。",
  CMChannel_localSettings_webtrends_reportId_displayName: "レポートID",
  CMChannel_localSettings_webtrends_reportId_emptyText: "ここにWebtrendsのレポートIDを入力します。",
  CMChannel_localSettings_webtrends_profileId_displayName: "プロファイルID",
  CMChannel_localSettings_webtrends_profileId_emptyText: "ここにWebtrendsのプロファイルIDを入力します。",
  CMChannel_localSettings_webtrends_liveUrlPrefix_displayName: "ライブURLのプレフィックス",
  CMChannel_localSettings_webtrends_liveUrlPrefix_emptyText: "ここにライブURLのプレフィックスを入力します。",
  CMChannel_localSettings_webtrends_userName_displayName: "ユーザー名",
  CMChannel_localSettings_webtrends_userName_emptyText: "ここにWebtrendsのユーザー名を入力します。",
  CMChannel_localSettings_webtrends_accountName_displayName: "アカウント名",
  CMChannel_localSettings_webtrends_accountName_emptyText: "ここにWebtrendsのアカウント名を入力します。",
  CMChannel_localSettings_webtrends_password_displayName: "パスワード",
  CMChannel_localSettings_webtrends_password_emptyText: "ここにWebtrendsのパスワードを入力します。",
  CMChannel_localSettings_webtrends_sortByMeasure_displayName: "並べ替え方法",
  CMChannel_localSettings_webtrends_sortByMeasure_emptyText: "ここに並べ替え方法の名前を入力します。",
  CMChannel_localSettings_webtrends_limit_displayName: "取得制限",
  CMChannel_localSettings_webtrends_limit_emptyText: "ここに収集する最大レコード数を入力します。",
  CMChannel_localSettings_webtrends_interval_displayName: "取得間隔",
  CMChannel_localSettings_webtrends_interval_emptyText: "ここにデータを収集する間隔（分単位）を入力します。0は取得を無効にします。",
  CMALXBaseList_localSettings_webtrends_userName_displayName: "ユーザー名",
  CMALXBaseList_localSettings_webtrends_userName_emptyText: "ここにWebtrendsのユーザー名を入力します。",
  CMALXBaseList_localSettings_webtrends_accountName_displayName: "アカウント名",
  CMALXBaseList_localSettings_webtrends_accountName_emptyText: "ここにWebtrendsのアカウント名を入力します。",
  CMALXBaseList_localSettings_webtrends_password_displayName: "パスワード",
  CMALXBaseList_localSettings_webtrends_password_emptyText: "ここにWebtrendsのパスワードを入力します。",
  CMALXBaseList_localSettings_webtrends_reportId_displayName: "レポートID",
  CMALXBaseList_localSettings_webtrends_reportId_emptyText: "ここにWebtrendsのレポートIDを入力します。",
  CMALXBaseList_localSettings_webtrends_profileId_displayName: "プロファイルID",
  CMALXBaseList_localSettings_webtrends_profileId_emptyText: "ここにWebtrendsのプロファイルIDを入力します。",
  CMALXBaseList_localSettings_webtrends_sortByMeasure_displayName: "並べ替え方法",
  CMALXBaseList_localSettings_webtrends_sortByMeasure_emptyText: "ここに並べ替え方法の名前を入力します。",
  CMALXBaseList_localSettings_webtrends_limit_displayName: "取得制限",
  CMALXBaseList_localSettings_webtrends_limit_emptyText: "ここに収集する最大レコード数を入力します。",
  CMALXBaseList_localSettings_webtrends_interval_displayName: "取得間隔",
  CMALXBaseList_localSettings_webtrends_interval_emptyText: "ここにデータを収集する間隔（分単位）を入力します。0は取得を無効にします。",
});
