CREATE DATABASE [cm_mcaefeeder]
GO
ALTER DATABASE [cm_mcaefeeder] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [cm_mcaefeeder] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET ANSI_NULLS OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET ANSI_PADDING OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET ARITHABORT OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [cm_mcaefeeder] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [cm_mcaefeeder] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET CURSOR_DEFAULT GLOBAL
GO
ALTER DATABASE [cm_mcaefeeder] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET DISABLE_BROKER
GO
ALTER DATABASE [cm_mcaefeeder] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [cm_mcaefeeder] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [cm_mcaefeeder] SET READ_WRITE
GO
ALTER DATABASE [cm_mcaefeeder] SET RECOVERY FULL
GO
ALTER DATABASE [cm_mcaefeeder] SET MULTI_USER
GO
ALTER DATABASE [cm_mcaefeeder] SET PAGE_VERIFY CHECKSUM
GO
USE [cm_mcaefeeder]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [cm_mcaefeeder] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

USE [master]
GO
CREATE LOGIN [cm_mcaefeeder] WITH PASSWORD=N'cm_mcaefeeder', DEFAULT_DATABASE=[cm_mcaefeeder], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [cm_mcaefeeder]
GO
CREATE USER [cm_mcaefeeder] FOR LOGIN [cm_mcaefeeder]
GO
USE [cm_mcaefeeder]
GO
ALTER USER [cm_mcaefeeder] WITH DEFAULT_SCHEMA=[cm_mcaefeeder]
GO
USE [cm_mcaefeeder]
GO
EXEC sp_addrolemember N'db_datareader', N'cm_mcaefeeder'
GO
USE [cm_mcaefeeder]
GO
EXEC sp_addrolemember N'db_datawriter', N'cm_mcaefeeder'
GO
USE [cm_mcaefeeder]
GO
EXEC sp_addrolemember N'db_ddladmin', N'cm_mcaefeeder'
GO

USE [cm_mcaefeeder]
GO
CREATE SCHEMA [cm_mcaefeeder] AUTHORIZATION [cm_mcaefeeder]
GO
USE [cm_mcaefeeder]
GO
ALTER USER [cm_mcaefeeder] WITH DEFAULT_SCHEMA=[cm_mcaefeeder]
GO
