CREATE DATABASE [cm_caefeeder]
GO
ALTER DATABASE [cm_caefeeder] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [cm_caefeeder] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [cm_caefeeder] SET ANSI_NULLS OFF
GO
ALTER DATABASE [cm_caefeeder] SET ANSI_PADDING OFF
GO
ALTER DATABASE [cm_caefeeder] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [cm_caefeeder] SET ARITHABORT OFF
GO
ALTER DATABASE [cm_caefeeder] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [cm_caefeeder] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [cm_caefeeder] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [cm_caefeeder] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [cm_caefeeder] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [cm_caefeeder] SET CURSOR_DEFAULT GLOBAL
GO
ALTER DATABASE [cm_caefeeder] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [cm_caefeeder] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [cm_caefeeder] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [cm_caefeeder] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [cm_caefeeder] SET DISABLE_BROKER
GO
ALTER DATABASE [cm_caefeeder] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [cm_caefeeder] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [cm_caefeeder] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [cm_caefeeder] SET READ_WRITE
GO
ALTER DATABASE [cm_caefeeder] SET RECOVERY FULL
GO
ALTER DATABASE [cm_caefeeder] SET MULTI_USER
GO
ALTER DATABASE [cm_caefeeder] SET PAGE_VERIFY CHECKSUM
GO
USE [cm_caefeeder]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [cm_caefeeder] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

USE [master]
GO
CREATE LOGIN [cm_caefeeder] WITH PASSWORD=N'cm_caefeeder', DEFAULT_DATABASE=[cm_caefeeder], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [cm_caefeeder]
GO
CREATE USER [cm_caefeeder] FOR LOGIN [cm_caefeeder]
GO
USE [cm_caefeeder]
GO
ALTER USER [cm_caefeeder] WITH DEFAULT_SCHEMA=[cm_caefeeder]
GO
USE [cm_caefeeder]
GO
EXEC sp_addrolemember N'db_datareader', N'cm_caefeeder'
GO
USE [cm_caefeeder]
GO
EXEC sp_addrolemember N'db_datawriter', N'cm_caefeeder'
GO
USE [cm_caefeeder]
GO
EXEC sp_addrolemember N'db_ddladmin', N'cm_caefeeder'
GO

USE [cm_caefeeder]
GO
CREATE SCHEMA [cm_caefeeder] AUTHORIZATION [cm_caefeeder]
GO
USE [cm_caefeeder]
GO
ALTER USER [cm_caefeeder] WITH DEFAULT_SCHEMA=[cm_caefeeder]
GO
