import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import LivecontextStudioPlugin_properties from "./LivecontextStudioPlugin_properties";

/**
 * Overrides of ResourceBundle "LivecontextStudioPlugin" for Locale "de".
 * @see LivecontextStudioPlugin_properties#INSTANCE
 */
ResourceBundleUtil.override(LivecontextStudioPlugin_properties, {
  CMMarketingSpot_text: "e-Marketing Spot",
  CMMarketingSpot_externalId_text: "e-Marketing Spot",
  CMMarketingSpot_externalId_tooltip: "Der verlinkte e-Marketing Spot",
  CMMarketingSpot_externalId_emptyText: "Ziehen Sie einen e-Marketing Spot aus der Bibliothek hierher.",
  CMProductTeaser_text: "Produktteaser",
  CMProductTeaser_externalId_text: "Produkt",
  CMProductTeaser_externalId_emptyText: "Ziehen Sie ein Produkt aus der Bibliothek hierher.",
  CMProductTeaser_productName_text: "Produktname",
  CMProductTeaser_productName_tooltip: "Name des verlinkten Produkts",
  CMProductTeaser_productShortDescription_text: "Produkt Kurzbeschreibung",
  CMProductTeaser_productShortDescription_tooltip: "Kurzbeschreibung des verlinkten Produkts",
  CMProductTeaser_pictures_text: "Angepasstes Teaserbild",
  CMProductTeaser_pictures_tooltip: "Angepasstes Teaserbild",
  CMProductList_text: "Produktliste",
  CMProductList_externalId_text: "Produktkategorie",
  CMProductList_externalId_tooltip: "Optional verlinkte Shop-Kategorie zur Auswahl der Produkte",
  CMProductList_externalId_emptyText: "Ziehen Sie eine Kategorie aus der Bibliothek hierher.",
  CMProductList_items_text: "Top Inhalte",
  CMProductList_items_tooltip: "Top Inhalte, die vor den Produkten dargestellt werden.",
  CMProductList_category_text: "Produktkategorie",
  "CMProductList_localSettings.productList_text": "Suchfilter",
  "CMProductList_localSettings.productList.facet.text": "Facette",
  "CMProductList_localSettings.productList.facet.emptyText": "Werte auswählen",
  "CMProductList_localSettings.productList.facetValue.text": "Facetten Wert",
  "CMProductList_localSettings.productList.facetValue.emptyText": "Auswählen",
  CMProductList_searchRefinement_text: "Sortierung der Suchergebnisse",
  "CMProductList_localSettings.productList.orderBy_text": "In welcher Reihenfolge sollen die Produkte sortiert werden?",
  "CMProductList_localSettings.productList.orderBy_tooltip": "Die Sortierreihenfolge der Suchergebnisse",
  "CMProductList_localSettings.productList.orderBy_emptyText": "Auswählen",
  "CMProductList_localSettings.productList.orderBy.ORDER_BY_TYPE_BRAND_ASC_text": "Brands",
  "CMProductList_localSettings.productList.orderBy.ORDER_BY_TYPE_CATEGORY_ASC_text": "Kategorien",
  "CMProductList_localSettings.productList.orderBy.ORDER_BY_TYPE_PRICE_ASC_text": "Preis - Aufsteigend",
  "CMProductList_localSettings.productList.orderBy.ORDER_BY_TYPE_PRICE_DSC_text": "Preis - Absteigend",
  "CMProductList_localSettings.productList.orderBy.ORDER_BY_TYPE_NAME_ASC_text": "Name - Aufsteigend",
  "CMProductList_localSettings.productList.orderBy.ORDER_BY_TYPE_NAME_DSC_text": "Name - Absteigend",
  "CMProductList_localSettings.productList.orderBy.ORDER_BY_TYPE_RELEVANCE_text": "Relevanz",
  "CMProductList_localSettings.productList.orderBy.ORDER_BY_TYPE_TOP_RATED_text": "Top Bewertet",
  "CMProductList_localSettings.productList.offset_text": "Ab welcher Position in der Suchergebnisliste sollen die Produkte dargestellt werden?",
  "CMProductList_localSettings.productList.offset_tooltip": "Die Startposition in der Suchergebnisliste",
  "CMProductList_localSettings.productList.offset_emptyText": "Auswählen",
  "CMProductList_localSettings.productList.maxLength_text": "Wieviele Elemente sollen maximal dargestellt werden?",
  "CMProductList_localSettings.productList.maxLength_tooltip": "Die Gesamtsumme der Suchergebnisse",
  "CMProductList_localSettings.productList.maxLength_emptyText": "Auswählen",
  CategoryFacetTagField_emptyText: "Werte auswählen",
  CategoryFacetFiltersGroup_emptyText: "Diese Kategorie hat keine Filter.",
  CategoryFacetFiltersGroup_noCategory: "Wählen Sie zuerst eine Kategorie aus.",
  CMProductList_facets_remove_invalid_values_description: "Die Suchfilterkonfiguration ist ungültig.",
  CMProductList_facets_remove_invalid_values: "Alle ungültigen Filter löschen",
  CMProductList_facets_text: "Suchfilter",
  CMProductTeaser_settings_inherit: "Einstellung von der Seite übernehmen",
  CMChannel_settings_inherit: "Einstellung von der übergeordneten Seite übernehmen",
  CMProductTeaser_settings_enabled: "Buttons und Detailsvorschau anzeigen",
  CMProductTeaser_settings_disabled: "Warenkorb-Funktionalität nicht anzeigen",
  "CMProductTeaser_localSettings.shopNow_text": "Warenkorb Funktionalität für Produktteaser",
  "CMChannel_localSettings.shopNow_text": "Warenkorb Funktionalität für Produktteaser",
  "CMTeaser_localSettings.useTeaserTargetValidity_true_text": "Teaser nur anzeigen, wenn das Teaser-Ziel gültig ist",
  "CMTeaser_localSettings.useTeaserTargetValidity_text": "Teaser nur anzeigen, wenn das Teaser-Ziel gültig ist",
  CMPicture_propertyGroup_commerce: "Zugewiesene Katalog-Einträge",
  "CMImageMap_localSettings.overlay.displayDefaultPrice_true_text": "Zeige Standardpreis",
  "CMImageMap_localSettings.overlay.displayDefaultPrice_text": "Zeige Standardpreis",
  "CMImageMap_localSettings.overlay.displayDiscountedPrice_true_text": "Zeige ermäßigten Preis",
  "CMImageMap_localSettings.overlay.displayDiscountedPrice_text": "Zeige ermäßigten Preis",
  "CMImageMap_localSettings.overlay.displayOutOfStockLink_true_text": "Zeige Verweis auf Out-Of-Stock Produktdetailseiten",
  "CMImageMap_localSettings.overlay.displayOutOfStockLink_text": "Zeige Verweis auf Out-Of-Stock Produktdetailseiten",
  "CMImageMap_localSettings.overlay.hideOutOfStockProducts_true_text": "Verstecke alle Out-Of-Stock Produkte",
  "CMImageMap_localSettings.overlay.hideOutOfStockProducts_text": "Verstecke alle Out-Of-Stock Produkte",
  CMVideo_productAssignments_title: "Produktzuweisungen",
  Commerce_Tab_attributes_title: "Attribute",
  Commerce_PropertyGroup_definingAttributes_title: "Definierende Attribute",
  Commerce_definingAttributes_emptyText: "Keine definierenden Attribute verfügbar.",
  Commerce_PropertyGroup_describingAttributes_title: "Beschreibende Attribute",
  Commerce_describingAttributes_emptyText: "Keine beschreibenden Attribute verfügbar.",
  Commerce_Tab_content_title: "Inhalt",
  Commerce_title_label: "Titel",
  Commerce_description_label: "Beschreibung",
  Commerce_shortDescription_label: "Kurzbeschreibung",
  Commerce_PropertyGroup_details_title: "Details aus dem Katalog",
  Commerce_Product_PropertyGroup_prices_title: "Preise",
  Commerce_Product_listPrice_label: "Listenpreis",
  Commerce_Product_listPrice_emptyText: "Kein Listenpreis verfügbar.",
  Commerce_Product_offerPrice_label: "Offerpreis",
  Commerce_Product_offerPrice_emptyText: "Kein Offerpreis verfügbar.",
  Commerce_Product_PropertyGroup_assets_title: "Assets",
  Commerce_Product_PropertyGroup_richMedia_title: "Bilder und andere Medien",
  Commerce_Product_richMedia_emptyText: "Keine Bilder oder Medien verfügbar.",
  Commerce_Product_assetMgmt_inactive_text: "Das Asset Management ist fü die Bilder und anderen Medien des Produkts nicht aktiviert.",
  Commerce_Product_PropertyGroup_downloads_title: "Downloads",
  Commerce_Product_downloads_emptyText: "Keine Downloads verfügbar.",
  Commerce_Tab_structure_title: "Katalogstruktur",
  Commerce_Product_PropertyGroup_category_title: "Kategorie",
  Commerce_Product_PropertyGroup_parentProduct_title: "Hauptprodukt",
  Commerce_Product_PropertyGroup_productVariants_title: "Produktvarianten",
  Commerce_Product_productVariants_emptyText: "Keine Produktvarianten verfügbar.",
  Commerce_Category_PropertyGroup_parentCategory_title: "Überkategorie",
  Commerce_Category_PropertyGroup_parentCategory_emptyText: "Dies ist eine Topkategorie und sie hat somit keine Überkategorie.",
  Commerce_Category_PropertyGroup_subcategories_title: "Unterkategorien",
  Commerce_Category_PropertyGroup_products_title: "Produkte",
  Commerce_Category_subcategories_emptyText: "Diese Kategorie hat keine Unterkategorien.",
  Commerce_Category_products_emptyText: "Diese Kategorie hat keine Produkte.",
  Commerce_Child_Categories_inherit_label: "Von der Kataloghierarchie erben",
  Commerce_Child_Categories_select_label: "Unterkategorien auswählen",
  Commerce_Category_Hierarchy_title: "Kataloghierarchie",
  Commerce_Category_Website_Navigation: "Seitennavigation",
  Commerce_Tab_system_title: "System",
  Commerce_PropertyGroup_filing_title: "Ablage",
  Commerce_store_label: "Store",
  Commerce_catalog_label: "Katalog",
  Commerce_id_label: "ID",
  Commerce_externalId_label: "External ID",
  Commerce_externalTechId_label: "External Tech. ID",
  Product_Link_empty_text: "Ziehen Sie ein Produkt aus der Bibliothek hierher.",
  Category_Link_empty_text: "Ziehen Sie eine Kategorie aus der Bibliothek hierher.",
  MarketingSpot_Link_empty_text: "Ziehen Sie einen Marketing Spot aus der Bibliothek hierher.",
  InheritReferencesAction_tooltip: "Klicken Sie diesen Button um die Katalogobjekt-IDs aus den XMP Bildmetadaten übernehmen",
  InheritReferencesAction_tooltipPressed: "Klicken Sie diesen Button um eigene Liste der Katalogobjekte zu definieren",
  InheritReferencesAction_text: "Katalogobjekt-IDs aus XMP Bildmetadaten zu übernehmen.",
  CMExternalChannel_text: "Augmentierte Kategorie",
  CMExternalChannel_toolTip: "Augmentierte Kategorie",
  CMExternalChannel_externalId_text: "Commerce-Referenz",
  CMExternalChannel_externalId_toolTip: "Zeigt auf eine externe Kategorie",
  CMExternalChannel_tab_PDP_pagegrid_title: "Produktinhalte",
  CMExternalChannel_pdpPagegrid_text: "Bereiche",
  "CMExternalChannel_pdpPagegrid.placements_2.layout_text": "Layout",
  "CMExternalChannel_pdpPagegrid-main_text": "Hauptbereich",
  "CMExternalChannel_pdpPagegrid-main_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-header_text": "Header",
  "CMExternalChannel_pdpPagegrid-header_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-footer_text": "Footer",
  "CMExternalChannel_pdpPagegrid-footer_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-footer-navigation_text": "Footer Navigation",
  "CMExternalChannel_pdpPagegrid-footer-navigation_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-sidebar_text": "Seitenleiste",
  "CMExternalChannel_pdpPagegrid-sidebar_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-tab_text": "Tab",
  "CMExternalChannel_pdpPagegrid-tab_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-banner_text": "Banner",
  "CMExternalChannel_pdpPagegrid-banner_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-additional_text": "Ergänzend",
  "CMExternalChannel_pdpPagegrid-additional_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-header-advertisement_text": "Header Werbung",
  "CMExternalChannel_pdpPagegrid-header-advertisement_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-footer-advertisement_text": "Footer Werbung",
  "CMExternalChannel_pdpPagegrid-footer-advertisement_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-navigationBar_text": "Navigationsleiste",
  "CMExternalChannel_pdpPagegrid-navigationBar_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-secondaryNav_text": "Zweite Navigationsleiste",
  "CMExternalChannel_pdpPagegrid-secondaryNav_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-footerSecondaryNav_text": "Untere Navigationsleiste",
  "CMExternalChannel_pdpPagegrid-footerSecondaryNav_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-topTeaser_text": "Teaser",
  "CMExternalChannel_pdpPagegrid-topTeaser_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-hero_text": "Hero Bereich",
  "CMExternalChannel_pdpPagegrid-hero_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-placement1_text": "Bereich 1",
  "CMExternalChannel_pdpPagegrid-placement1_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-placement2_text": "Bereich 2",
  "CMExternalChannel_pdpPagegrid-placement2_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-placement3_text": "Bereich 3",
  "CMExternalChannel_pdpPagegrid-placement3_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-above_text": "Oberhalb Hauptbereich",
  "CMExternalChannel_pdpPagegrid-above_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-below_text": "Unterhalb Hauptbereich",
  "CMExternalChannel_pdpPagegrid-below_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalChannel_pdpPagegrid-product-detail_text": "Produkt Details",
  "CMExternalChannel_pdpPagegrid.placements_2.placements.content/{placementId:[0-9]+}.extendedItems.{index:[0-9]+}.visibleFrom_text": "Sichtbar von",
  "CMExternalChannel_pdpPagegrid.placements_2.placements.content/{placementId:[0-9]+}.extendedItems.{index:[0-9]+}.visibleTo_text": "Sichtbar bis",
  CMExternalProduct_text: "Augmentiertes Produkt",
  CMExternalProduct_toolTip: "Augmentiertes Produkt",
  CMExternalProduct_externalId_text: "Commerce-Referenz",
  CMExternalProduct_externalId_toolTip: "Zeigt auf ein externes Produkt",
  CMExternalProduct_tab_pagegrid_title: "Produktinhalt",
  CMExternalProduct_pdpPagegrid_text: "Bereiche",
  "CMExternalProduct_pdpPagegrid.placements_2.layout_text": "Layout",
  "CMExternalProduct_pdpPagegrid-main_text": "Hauptbereich",
  "CMExternalProduct_pdpPagegrid-main_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-header_text": "Header",
  "CMExternalProduct_pdpPagegrid-header_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-footer_text": "Footer",
  "CMExternalProduct_pdpPagegrid-footer_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-footer-navigation_text": "Footer Navigation",
  "CMExternalProduct_pdpPagegrid-footer-navigation_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-sidebar_text": "Seitenleiste",
  "CMExternalProduct_pdpPagegrid-sidebar_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-tab_text": "Tab",
  "CMExternalProduct_pdpPagegrid-tab_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-banner_text": "Banner",
  "CMExternalProduct_pdpPagegrid-banner_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-additional_text": "Ergänzend",
  "CMExternalProduct_pdpPagegrid-additional_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-header-advertisement_text": "Header Werbung",
  "CMExternalProduct_pdpPagegrid-header-advertisement_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-footer-advertisement_text": "Footer Werbung",
  "CMExternalProduct_pdpPagegrid-footer-advertisement_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-navigationBar_text": "Navigationsleiste",
  "CMExternalProduct_pdpPagegrid-navigationBar_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-secondaryNav_text": "Zweite Navigationsleiste",
  "CMExternalProduct_pdpPagegrid-secondaryNav_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-footerSecondaryNav_text": "Untere Navigationsleiste",
  "CMExternalProduct_pdpPagegrid-footerSecondaryNav_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-topTeaser_text": "Teaser",
  "CMExternalProduct_pdpPagegrid-topTeaser_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-hero_text": "Hero Bereich",
  "CMExternalProduct_pdpPagegrid-hero_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-placement1_text": "Bereich 1",
  "CMExternalProduct_pdpPagegrid-placement1_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-placement2_text": "Bereich 2",
  "CMExternalProduct_pdpPagegrid-placement2_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-placement3_text": "Bereich 3",
  "CMExternalProduct_pdpPagegrid-placement3_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-above_text": "Oberhalb Hauptbereich",
  "CMExternalProduct_pdpPagegrid-above_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-below_text": "Unterhalb Hauptbereich",
  "CMExternalProduct_pdpPagegrid-below_emptyText": "Ziehen Sie Inhalte aus der Bibliothek hierher.",
  "CMExternalProduct_pdpPagegrid-product-detail_text": "Details",
  "CMExternalProduct_pdpPagegrid.placements_2.placements.content/{placementId:[0-9]+}.extendedItems.{index:[0-9]+}.visibleFrom_text": "Sichtbar von",
  "CMExternalProduct_pdpPagegrid.placements_2.placements.content/{placementId:[0-9]+}.extendedItems.{index:[0-9]+}.visibleTo_text": "Sichtbar bis",
  EnhancedPageGroup_title: "Erweiterte Seite",
  CMExternalPage_text: "Augmentierte Seite",
  CMExternalPage_toolTip: "Augmentierte Seite",
  CMExternalPage_externalId_text: "Externe Seiten ID",
  CMExternalPage_externalId_emptyText: "Geben Sie die externe Seiten ID hier ein.",
  CMExternalPage_externalUriPath_text: "Externer URI Pfad",
  CMExternalPage_externalUriPath_emptyText: "Geben Sie den externen URI Pfad hier ein (inklusive Parameter).",
  TreeView_catalog: "E-Commerce",
  CatalogView_invalid_store_text: "Bitte eine Site mit gültigem E-Commerce-Katalog auswählen.",
  CatalogView_empty_text: "Die Liste ist leer.",
  Catalog_DragDrop_multiSelect_text: "{0} ausgewählte Katalog-Einträge",
  description_header: "Beschreibung",
  Action_searchProductVariants_text: "Suche Produktvarianten",
  Action_searchProductVariants_tooltip: "Suche Produktvarianten",
  Action_searchProductPictures_text: "Suche Produktbilder",
  Action_searchProductPictures_tooltip: "Suche Produktbilder",
  Action_openInManagementCenter_text: "In WCS-Management öffnen",
  Action_openInManagementCenter_tooltip: "In WCS-Management öffnen",
  Action_openManagementCenter_text: "Management Center",
  Action_openManagementCenter_tooltip: "Management Center öffnen",
  Action_createProductTeaser_text: "Produktteaser anlegen",
  Action_createProductTeaser_tooltip: "Teaser für Produkt oder Produktvariante anlegen",
  Action_augmentCategory_text: "Kategorie augmentieren",
  Action_augmentCategory_tooltip: "Kategorie augmentieren",
  Action_augmentProduct_text: "Produkt augmentieren",
  Action_augmentProduct_tooltip: "Produkt augmentieren",
  Action_createMarketingSpot_text: "e-Marketing Spot anlegen",
  Action_createMarketingSpot_tooltip: "e-Marketing Spot anlegen",
  Action_removeCommerceSegment_text: "Entfernen",
  Action_removeCommerceSegment_tooltip: "Das E-Commerce-Benutzersegment von der Kundenpersona entfernen",
  Action_removeCommerceContract_text: "Entfernen",
  Action_removeCommerceContract_tooltip: "Das E-Commerce-Benutzerkontrakt von der Kundenpersona entfernen",
  Action_deleteContentProxy_text: "Augmentation entfernen",
  Action_deleteContentProxy_tooltip: "Augmentation entfernen",
  Action_withdrawContentProxy_text: "Augmentation zurückziehen",
  Action_withdrawContentProxy_tooltip: "Augmentation zurückziehen",
  commerceConnectionError_title: "Fehler",
  commerceConnectionError_message: "Konnte Katalog nicht erreichen ('{0}'). Bitte kontaktieren Sie Ihren Systemadministrator, wenn dieses Problem fortlaufend auftritt.",
  commerceCatalogError_title: "Fehler",
  commerceCatalogError_message: "Ein Katalogfehler ist aufgetreten('{0}'). Bitte kontaktieren Sie Ihren Systemadministrator, wenn dieses Problem fortlaufend auftritt.",
  HeaderToolbar_workspaceSelector_empty_text: "E-Commerce-Workspace auswählen.",
  commerce_workspace_invalid: "Workspace ({0}) nicht gefunden.",
  commerce_workspace_no_workspace: "Kein Workspace",
  Category_augmentedMessage_title: "Kategorie augmentiert",
  Category_augmentedMessage_text: "Die Kategorie '{0}' ist nun augmentiert mit Content aus dem Repository. Die augmentierte Kategorie wird nun angezeigt.",
  Product_augmentedMessage_title: "Produkt augmentiert",
  Product_augmentedMessage_text: "Das Produkt '{0}' ist nun augmentiert mit Content aus dem Repository. Das augmentierte Produkt wird nun angezeigt.",
  p13n_commerce_group_label: "E-Commerce-System",
  p13n_commerce_user_segments_label: "Benutzersegmente",
  p13n_commerce_user_segments_selector_emptyText: "E-Commerce-Benutzersegment auswählen.",
  p13n_commerce_user_segments_selector_for_persona_emptyText: "Ein E-Commerce-Benutzersegment zur Kundenpersona hinzufügen.",
  p13n_commerce_user_segment_invalid: "Ungültige E-Commerce-Benutzersegment-ID: {0}",
  p13n_commerce_user_contracts_label: "Benutzerkontrakte",
  p13n_commerce_user_contracts_selector_emptyText: "E-Commerce-Benutzerkontrakt auswählen.",
  p13n_commerce_user_contracts_selector_for_persona_emptyText: "Ein E-Commerce-Benutzerkontrakt zur Kundenpersona hinzufügen.",
  p13n_commerce_user_contract_invalid: "Ungültige E-Commerce-Benutzerkontrakt-ID: {0}",
  p13n_commerce_no_store_configured: "Es ist kein E-Commerce-Katalog konfiguriert.",
  p13n_context_commerce_segment: "E-Commerce-Benutzersegment",
  p13n_context_commerce_segment_invalid: "Das E-Commerce-Benutzersegment wurde nicht gefunden.",
  p13n_persona_commerce_segments_empty: "Keine E-Commerce-Benutzersegmente definiert.",
  p13n_persona_commerce_contracts_empty: "Keine E-Commerce-Benutzerkontrakte definiert.",
  AugmentedCategory_help_productpagegrid_tooltip: "Die Produktdetailseiten aller Produkte in dieser Kategorie verwenden diese Bereiche.",
  Facet_Dropdown_ParentCatalogGroup: "Unterkategorien",
  Facet_Dropdown_ManufacturerName: "Herstellername",
  Facet_Dropdown_OfferPrice_USD: "Angebotspreis in USD",
  Facet_Dropdown_OfferPrice_EUR: "Angebotspreis in EUR",
  Facet_Dropdown_gender: "Geschlecht",
  Preview_Wcs_Timezone_Divergation_Warning_Message: "Die ausgewählte Zeitzone für die Vorschau unterscheidet sich von der Zeitzone des WCS-Servers (<span class=\"font-weight-bold\">{0}<\/span>).",
});
